### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Zagicien** [danny0838/webscrapbook#105]
Hi,
it would be nice if the option "Download linked files" download the resources of the Downloaded linked files.
Eg : < a href="**h ttps://website.com/va/ga.html**">Download all images from h ttps://website.com/va/ga.html</ a>

**Comment by Zagicien** [comment]
Also, it would be nice if the option "Download linked files" download an image of a referrer website.
Eg : < a href="h ttps://dereferer.com/?**h ttps://website.com/va/image.jpg**">Download image from h ttps://website.com/va/image.jpg</ a>

**Comment by Zagicien** [comment]
Sometimes when Save captured data as Folder, it downloads a empty file (instead of a folder) and nothing happens.

**Comment by danny0838** [comment]
Please be more specific about your title and content. It seems that F1 is about the in-depth capture of legacy ScrapBook and is out of the scope of download linked files feature; and F2 seems to be exactly the current download linked files does and I don't get what your request is for. (FYI: you can use "`" to escape the text so that it doesn't have syntax parsed.)

F3 seems to be a totally different issue. Please raise it as another issue and be more clear about it (please describe what "sometimes" is, e.g. what your capture options is, what is the URL you are capturing, etc.)

**Comment by danny0838** [comment]
Close stale issue without valid information.
