### ISSUE TITLE
[Bug] "Styled components" css not captured 

### ISSUE THREAD

**Issue by andre-gois** [danny0838/webscrapbook#109]
Hi, great project!

When saving pages that are built with "Styled Components" (for exemple the library page itself
https://www.styled-components.com ) the page styles are not saved at all.

**Comment by danny0838** [comment]
This issue is something like #70 that stylesheets of a Reddit.com page are lost after captured, as Reddit.com uses styled-components.

What WSB captures is source stylesheet texts, while styled-components uses <code>[insertRule](https://developer.mozilla.org/docs/Web/API/CSSStyleSheet/insertRule)</code>-like technique to inject CSS dynamically into the document and source stylesheet texts are cleared afterwards.

To capture the injected stylesheets, we have to capture stylesheets from CSSOM, such as <code>[Document.stylesheets](https://developer.mozilla.org/docs/Web/API/Document/styleSheets)</code>, instead. This raises further issues, however:

1. Current browser implementation of CSSOM preserves only parsed stylesheet rules, and thus CSS comments and rules not recognized by the browser (such as a vendor prefixed rule or a CSS hack for specific browser) are lost, making the captured web page less platform compatible.

2. Cross-domain stylesheets cannot be accessed from CSSOM, as described in #43.

As most web sites do not use such technique, current implementation (i.e. capture raw stylesheet texts) is generally more faithful. We may add an option to capture stylesheets from CSSOM in the future if we have with a solution to issue 2.

By the way, styled-components seems to read from source stylesheet texts, do some minor modification, and then re-inject to the document, and therefore source stylesheet texts seems accessible via `capture (source)`. You may use it as a temporary workaround.

**Comment by andremoniz** [comment]
@danny0838 hi thanks for the clarification. 
Can you please explain better the workaround?

**Comment by danny0838** [comment]
@andremoniz That is, use ``

**Comment by andremoniz** [comment]
I am sorry but i still cannot understand what you mean. Can you please elaborate ? Thanks

**Comment by danny0838** [comment]
Implemented a quick fix (493e0611e0c4c3dbb5d8844ebdd0920cdf607803) in [0.44.0](https://github.com/danny0838/webscrapbook/releases/tag/0.44.0).

This issue has a deeper aspect and requires a large code structure rework to solve. Fortunately it is very unlikely used in practical cases. For now we solve the most visible part first.

**Comment by danny0838** [comment]
Implemented full support of dynamic CSS in [0.45.0](https://github.com/danny0838/webscrapbook/releases/tag/0.45.0) (esp. 00b6df1a66f46c1b9d01a499d9835962534e2335).
