### ISSUE TITLE
stall on capture and capture source firefox 60.6.2esr in linux 64bits 2

### ISSUE THREAD

**Issue by ag88** [danny0838/webscrapbook#112]
oops, a repeat issue (https://github.com/danny0838/webscrapbook/issues/111), but this time round a different error, 

![capture error](https://i.imgur.com/gIoNJZy.png "capture error")

```
Capturing (document) [124] https://github.com/danny0838/webscrapbook/issues/111 ... Error downloading file (): Requires an absolute URL.
Error downloading file (): Requires an absolute URL.
Error downloading file (): Requires an absolute URL.
Done.
```
in the same way the error is displayed after the frame is resized (i waited a while like 30 secs before resizing the frame just so that saving can happen first. i think it would be good to place some indicator that saving is on-going. 

one thing though, in the webscrapbook save folder, i found a sub-folder in which the contents of the page is saved, i.e. all the images and index.html itself.
just that the compressed single file is not found

**Comment by ag88** [comment]
one thing though, in the webscrapbook save folder, i found a sub-folder in which the contents of the page is saved, i.e. all the images and index.html itself.
just that the compressed single file is not found

**Comment by danny0838** [comment]
A yellow message is warning rather than error. The capture is considered success if there is no error, but there could be something wrong and need adjustment if there's a warning. Such warning is sometimes caused by bad URLs in the source web page or inserted by another browser extension. In your case, it's due to three `<img>` elements with `src` attribute set to empty string, which is a bad practice, in the source GitHub page.

On the other hand, what do you mean that "just that the compressed single file is not found"?

**Comment by ag88** [comment]
oops, it is my goof ! yup setting it as ``MAFF file `` instead of `` Folder `` in options solved it !
thanks !
