### ISSUE TITLE
Put an item at [the top of a folder | the bottom of a folder]

### ISSUE THREAD

**Issue by smoith** [danny0838/webscrapbook#120]
Can it be possible to have an option to put an item at the top of a folder. By default it is placed at the bottom of a folder.

**Comment by danny0838** [comment]
Possible. But we haven't yet got a time to implement it.

**Comment by danny0838** [comment]
Although this should be technically possible. It's still somehow troublesome to implement due to the asynchronous nature of the WebExtension framework.

There are also some designing issue that may be controversial and need to be discussed in prior to prevent a confusion of the user...

A\. What should this apply? It seems possible to affect:

1. Newly captured item.
2. Newly created item, such as folder, separator, note, postit, etc.
3. Moving an item under an item.

However, does everyone really want all of them, or just some of them? This may need some discussion.

B\. What should the behavior be if multiple items are to be inserted? If there are currently `X, Y, Z` in a folder `myfolder`.

1. What if the user run a batch capture of pages `A, B, C` to `my folder`? Should it be `A, B, C, X, Y, Z` or `C, B, A, X, Y, Z`?
2. What if the user drags items `A, B, C` into `my folder`? Should it be `A, B, C, X, Y, Z` or `C, B, A, X, Y, Z`?

We may not consider implementation before 1.0 if these issue cannot be resolved.

**Comment by danny0838** [comment]
@smoith @tomlokiston We are evaluating whether to implement this feature in [v2.0](https://github.com/danny0838/webscrapbook/issues/338)

Due to the async and server-client nature of the new browser extension framework, there may be an issue if this feature is configured only at the client side. We plan to implement this as a new book config—a book with the config like `book.<book_id>.new_at_top` set to true gets new items inserted at top of tree.

Checking the behavior of legacy ScrapBook (X), moving (or copying) items `A, B, C` into a folder having `X, Y, Z` gets `C, B, A, X, Y, Z`. We consider this a bad feature and will change it to `A, B, C, X, Y, Z`, with the rationale that moved items should keep the original tree order, and that a tree with `new items at top` should mean that items are ordered from bottom to top, and thus moving `A, B, C` into `X, Y, Z` should be treated as moving each item from bottom to top to the position before X, i.e.:
1. Move `C` and insert at the first position => `C, X, Y, Z`
2. Move `B` and insert at the first position => `B, C, X, Y, Z`
3. Move `A` and insert at the first position => `A, B, C, X, Y, Z`

This does not affect inserting items from other sources, i.e. capturing pages `A, B, C` into a folder having `X, Y, Z` will get `C, B, A, X, Y, Z` at last.

Please provide a feedback if you have an opinion or good idea about this.
