### ISSUE TITLE
[Feature request] Disable Locate, Edit, Save toolbar by default

### ISSUE THREAD

**Issue by cy7yz2rj** [danny0838/webscrapbook#121]
Running version 0.49.0 of WS in Firefox, every page now displays a toolbar at the bottom.

Is there any way to permanently disable it? If not, please make a new setting to do so.

**Comment by jccalhoun** [comment]
I'm also getting this with Firefox 70 beta on Win10.

**Comment by ssokolow** [comment]
I just started seeing this "mysterious toolbar" at the bottom of the Fanfiction.net chapters I was reading. I was only able to identify the source by pointing the DOM Inspector at it.

Since I can't see any obvious way to disable it in the addon options, I'm now debating whether to disable WebScrapbook or downgrade to an earlier version and disable updates.

**Comment by danny0838** [comment]
The editor toolbar is meant to shown only when a captured page hosted by the backend server is visited. Being visible on all web pages is a current bug. A temporary workaround is to fill an address in the server url in the options.

Sorry for the inconvenience. We'll fix the bug soon, and will add an option to determine whether to load the toolbar automatically.

**Comment by cy7yz2rj** [comment]
Fixed in v0.50.0, thanks!
