### ISSUE TITLE
Inconsistent behaviour when capturing pages with user hidden elements

### ISSUE THREAD

**Issue by cy7yz2rj** [danny0838/webscrapbook#122]
uBlock Origin's cosmetic filters can be used to alter a page's appearance. uBO offers 2 means to achieve this: temporary filters created with the [zapper](https://github.com/gorhill/uBlock/wiki/Element-zapper) which are disabled on page reload, and permanent filters.

Web ScrapBook treats the 2 types differently when capturing pages with hidden elements.

Previously created permanent filters are completely ignored, leading to a mismatch between the displayed and captured pages and larger file size because permanently hidden elements are captured.

However, WS recognises temporary filters and permanent filters made immediately before capturing (no reloads) and such elements are (correctly) excluded from capture.

**Comment by danny0838** [comment]
Thank you for reporting. Could you provide a reproducible example? Such as a web page URL and the configs of uBO.

**Comment by cy7yz2rj** [comment]
I re-tested with a fresh profile of Firefox 60.9.0esr (64-bit) on Debian, uBO and WS installed from AMO, default settings for all.

I couldn't reproduce my previous report of WS applying temporary filters and newly-made permanent ones equally; now permanent filters were always ignored, temporary filters always applied.

Steps to reproduce:
1. fresh profile, install uBO + WS from AMO, default settings
2. load this issue page
3. capture normally for reference
4. remove all visible elements with the zapper (temporary filters) and capture, only index.html, stylesheets and favicon should be present in the capture folder
5. reload page to reset appearance
6. same as 4 but using the picker (permanent filters) and capture, captured files should be virtually identical to the reference

**Comment by danny0838** [comment]
Can you provide the URL of the issue page(s)?

**Comment by cy7yz2rj** [comment]
https://github.com/danny0838/webscrapbook/issues/122

Any web page will do I think, though one with large image files would probably be a better example to show the impact of ignoring blocked images in the capture file size.

**Comment by cy7yz2rj** [comment]
Another test, another outcome. What happened this time:

1. Firefox 60.9.0esr (64-bit), fresh profile, uBO 1.18.4, WS 0.52.2 from AMO, default settings for all
2. load this page https://github.com/danny0838/webscrapbook/issues/122
3. capture reference: ~712 KiB, index.html, 3 CSS, favicon, 1 GIF, 1 SVG, 2 JPEG, 2 PNG, captured page displays as expected (default)
4. zap all elements and capture: ~623 KiB, index.html, 3 CSS, favicon, captured page displays as expected (blank)
5. reload to reset
6. use picker to remove all elements and capture: ~712 KiB, index.html, 3 CSS, favicon, 1 GIF, 1 SVG, 2 JPEG, 2 PNG, captured page as expected (blank as in 4). This clashes with my test yesterday
7. reload page, uBO permanent filters sitll in effect so it's still blank in the browser window, capture again: ~712 KiB, index.html, 3 CSS, favicon, 1 GIF, 1 SVG, 2 JPEG, 2 PNG, captured page displays like the reference as if no filters were being used

**Comment by danny0838** [comment]
1\. There's no so-called "temporary filter". What zipper does is exactly removing an element, which can be confirmed by the official documentation and the developer tool.

2\. What uBO's permanent filter does is by injecting CSS declarations directly into the target frame, and these CSS declarations are not accessible by scripts of the web page and other extensions. Even if they are accessible, we won't get a reduced page size as it's an additional CSS rules rather than removing web page elements.

3\. The only workaround seems to be implementing [the feature to remove hidden elements (more specifically, those with computed CSS property of "display" to be "none")](https://github.com/danny0838/webscrapbook/issues/114) during the capture process, with several caveats:
1. This won't work when the page isn't really loaded in a tab (e.g. capture source).
2. The browser cannot tell apart CSS injected by ad-blocker extensions from normal page CSS and other user stylesheets. And  removal of all "display: none" elements is not safe—the page might be altered with CSS having changed targets of a selector like `:nth-child`.

**Comment by danny0838** [comment]
https://github.com/danny0838/webscrapbook/issues/122#issuecomment-535576539 has been implemented in 0.53.

**Comment by cy7yz2rj** [comment]
Many thanks for this new feature, seems to work as I hoped.
