### ISSUE TITLE
Can we have the ability to block saving data from domains like ad servers?

### ISSUE THREAD

**Issue by bulrush15** [danny0838/webscrapbook#123]
Ad servers can really slow down the capture process. I'd like the ability to block saving elements from certain domains like ad servers. But also sometimes I don't want to save comments from Disqus either. Can you add that as a new feature? 

Thanks.

**Comment by maxnikulin** [comment]
Does not scrapbook capture current DOM state, so ads could be stripped by dedicated extensions like uBlock or AdBlockPlus prior to scrapbook action?

**Comment by danny0838** [comment]
It depends on how the ad blockers work. Many ad blockers doesn't remove blocked elements but hide them by injecting an extension CSS, which is not accessible by WSB. Currently the nearest way is to active "remove hidden elements", with several caveats. See #122.

**Comment by maxnikulin** [comment]
My bad. I realized that I am avoiding ads on captured pages because of ad blockers prevent fetching of JavaScript that loads banners. As a result img elements are not added to DOM, so blockers work to some extent. Usually I select the main part of the page as well, so static top/bottom banners are not a problem as well.

From the noise around declarativeNetRequest/webRequest API I expected more severe methods against images. It's a pity that rich uBlock origin features could not be combined with WebScrapBook just by installing both extensions.

As to "remove hidden elements" and various (`nth-element`, etc.) CSS decorations, it might help to replace `href` in hidden `img` elements to e.g. 1x1.png.

**Comment by danny0838** [comment]
Unfortunately, it's impossible for WebScrapBook to know whether a resources is blocked by another ad-blocking extension, as every extension are independent to each other, unless the author explicitly implements an API for another extension to call.

Besides cosmetic blocking (i.e. hiding elements via CSS selectors) with `remove hidden elements`, another way to block resources on a 3rd party site is using the capture helper.
