### ISSUE TITLE
Is webscrapbook going to be more similar to scrapbookX ?

### ISSUE THREAD

**Issue by Iraito** [danny0838/webscrapbook#13]
I installed the add-on but as of now it seems like an alpha version, i can't edit webpages before saving them, there's no menu, webpages have to be manually saved to a specific folder (having the scrapbook folder in profiles was perfect) and so on.

Are things going to change before the release of firefox 57 ? and will we be able to import our scrapbookX pages to webscrapbook ?

**Comment by danny0838** [comment]
It depends.

Technically speaking, due to the restriction of the current WebExtension framework, it is impossible to simply same and edit files from the local drive. Some workarounds may work, such as:

1. Save everything to the browser database, and load via the viewer: this could work quite much like ScrapBook X, but all files are not in the local drive and cannot be easily edited or synced to another terminal via Dropbox or so.

2. Use native messaging and external application: this could work just like ScrapBook, but the installation of external application and native messaging could be complicated and unfriendly to the user. And it could also expose a security risk.

Both seem technically possible, but still require further investigation. If none are viable, Web ScrapBook would probably focus only on capturing web pages and view archived files, and leave the management functionality to other applications.

Edit before save is also technically possible, but we need some idea and evaluation for how to build the AI. Before that, the built-in browser toolbox already provides a lot of good features to edit the web page, and you can simply use that.

Whether ScrapBook X data could be imported to Web ScrapBook depends on how they are stored at last. As for now, there is a ScrapBook X Converter that can convert ScrapBook X pages to zip, maff, and single HTML file.

**Comment by Atanacius** [comment]
I follow your ScrapBook X since ScrapBook/ScrapBook PLUS is.. now dead (since their authors hasn't updated it for years..)

Anyway, I want point a solid finger on Web Extensions that Firefox impose us:
It's now breaking MANY MANY MANY extensions, 
but in final with a little work (for small extensions based on XUL), 
and with many many many work (for complex extensions based on XUL aswell, like ScrapBook X), 
it's possible to workaround each of these stuff.

And I don't see ANY problems by installing a third party app for editing ScrapBook pages (under Web Extensions), it just need to be: clever, smart, simple (keeping the KISS concept in mind) and also... NOT FULL OF ADWARES :)

That's said, I think, if small external "editor" can be run when we want edit pages saved in our ScrapBook library, (like a clone of WYSIWYG as FCKEditor and cie..), it must be reliable enough to honoring the ScrapBook structure !

I KNOW you're going in much of troubles danny0838 !
But in final, if you provide yourself (-developping yourself-) an external editor that rely on let's said: ELECTRON framework it will be reliable enough to be installed just at a side of the "Scrapbook Web" extension addon page.

Like: "If you want edit your page saved under ScrapBook, please note as the Web Extension format to write Firefox extension will not let ScrapBook to edit the same way your page like it was before, you will be required to install this little software that work like a HTML Editor based on Electron framework and we are the authors of this editor aswell !"

It will be reliable enough!

As final words, I want add: keep the good work, users will follow orders for making the right features working as before, if they want EDIT, then they will install your addon software for editing page, if not, this mean they only want saving/archive their discovers on Internet :) !

Do not give up, the communauty will certainly be upset to not have a ScrapBook WE !!
Not upset to you, but upset to Firefox and ... mostly Firefox team (but that is another debate will not take place here!)

Thanks for reading and sorry for the looong loong piece of text!

**Comment by Atanacius** [comment]
Also I read out this on somewhere:

"Looking at what the add-on does, it should be portable to WE: content script or downloads API to save pages, chrome.storage with larger storage quota, sidebar API... One thing that won't be possible will be filesystem integration, but the add-on can make its own fs using IndexedDB or chrome.storage, and urls can be opened via the blob: scheme
"

Don't know if it's applicable to Firefox 57+ Web Extensions APIs !

**Comment by danny0838** [comment]
Note: To avoid a distraction, we are going to focus similar discussion in #2. Please go there for such issues.
