### ISSUE TITLE
content search doesn't work

### ISSUE THREAD

**Issue by kang2chain** [danny0838/webscrapbook#154]
I think this extension is really awesome! Many functions work best .
But when I use the content search , it seems not to work , it just can search the title.

**Comment by danny0838** [comment]
Do you mean the search page from the search button of the sidebar? Have you created a fulltext cache?

**Comment by kang2chain** [comment]
I use the backend server , and when i searched first time , it tips that i need make a index , so i made 
but it still just can search the title , not working for content

**Comment by kang2chain** [comment]
> Do you mean the search page from the search button of the sidebar? Have you created a fulltext cache?

Sorry I found the problem , I just made the index , didn't made the cache . Thanks for your time.

**Comment by danny0838** [comment]
Could you explain a little more about "made the index, didn't made the cache"? I don't quite understand it. Just out of curiosity.

**Comment by kang2chain** [comment]
> Could you explain a little more about "made the index, didn't made the cache"? I don't quite understand it. Just out of curiosity.

I thought it wrong haha , it is the same thing , "made the index" means that when i searched first time , it tips that i need make a index
and "made the cache" means that Generate site index -> Index for server 
that is to say when I update my page , I should do the "index for server" manually for content search
maybe autoupdate is better

**Comment by danny0838** [comment]
That's bizarre. If you visit the search page for the first time, it should be showing something like this:

![圖片](https://user-images.githubusercontent.com/531417/80623589-02c17780-8a7d-11ea-804d-ae26a32e62b9.png)

which says "cache" instead of "index", and already provides a link to generate the cache.

Auto-update is probably undesirable since the fulltext cache can be large and an update may take 30~90 seconds or even more.
