### ISSUE TITLE
[Feature Request] Saving Pages Into Tree Structure

### ISSUE THREAD

**Issue by superjkl** [danny0838/webscrapbook#161]
Thanks for the work you've been putting into the migration! There is just one feature missing which was in ScrapBook X and it is the ability to choose where in the tree a page is saved. This was all available in the context menu. I know you're having issues with accessing the filesystem without the server, so I was wondering if this option could be available if the server is being used.

**Comment by danny0838** [comment]
This is technically possible, but still not quite easy to implement.

This is a duplication of  #37 so we'll simply trace it there.

**Comment by superjkl** [comment]
Are you looking for help on this project? I'd love to contribute, but I'd need an explanation of the structure of the code and general design patterns used.

**Comment by danny0838** [comment]
@superjkl Welcome for contribution. We don't set any hard limit and it's free to simply work on it and issue a pull request, and we can discuss it further and make required modification afterwards. However there are still many things to be improved and some code are possibly to be refactored. We currently cannot provide a clear documentation. It's more recommended to inform which part you're going to work on beforehand, so that we can better integrate it and prevent a potentially conflicting work.

**Comment by superjkl** [comment]
Sounds good, I agree refactoring should be a priority for maintainability. I'll setup a pull request soon.

**Comment by superjkl** [comment]
I just tried out 0.76 and it was awesome! I realized that I could easily use the sidebar to drag and drop all highlighted pages into a folder, so it wasn't necessary to save directly to the folder. I can't wait to use this!
