### ISSUE TITLE
InDepth capture as ScrapBook X

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#164]
(excerpted from #153)

Current investigation suggests that a code rework is required to support it. There are also design issues such as how to keep a map of the saved resources and metadata, as the original design of legacy ScrapBook has many issues, and we may need some ideas about that.

We are still not sure whether it can really be done or not. This has been regarded as a minor feature as ScrapBook is basically designed to capture the currently rendered page and not for headlessly capturing a whole site, which can be done by lots of good spider tools. If we cannot do that we may consider an alternative or just forget about it.

**Comment by spiralofhope** [comment]
I have and still do use this feature; it's incredible to create a navigable snapshot of a page and sub-pages rather than hunt down every strangely-linked sub-page.

Although I really like being able to easily save things within ScrapBook X, it's okay for you to declare this feature as out-of-scope for your efforts and then your time can be spent on other things.

If there is separate spidering software, then suggestions are welcome.  A while ago I had tried some software but it was all awful; that's what led me to this project.  Doing it in-browser has made life much easier.

My simplest use case is to download sub-pages of the current one, which lets me capture gallery sub-pages.  However, I use 
[DownThemAll!](https://www.downthemall.org/) for that. ([notes](https://blog.spiralofhope.com/?p=6545))

**Comment by danny0838** [comment]
Fortunately we have found a way to implement it, and it is available in 0.92.0.

Currently we haven't found a way to pause/resume and change pages to download in real time, pages can only be filtered with pre-configured filters.

I'd also like to know whether you are still using sitemap and capture again for a deeply captured page? There are still some issues for these features and we may need some ideas/suggestions about them, or may consider just not implement them.

**Comment by spiralofhope** [comment]
> I'd also like to know whether you are still using sitemap and capture again for a deeply captured page?

I've never found a more convenient way to do deep downloads with other software; it's a wonderful feature to have in the browser.

People have said there are these other tools like `wget`, but they are opaque to use.  I'd be comfortable being told what I should learn, and then I can become a little expert at it and can provide documentation for others who miss this feature from ScrapBook X.

**Comment by danny0838** [comment]
What do you think about the current implementation in 0.92.0+?

Some tools that can for reference: `wget` (CLI tool with support of recursive web page capture), `httrack` (CLI/GUI tool designed for web site mirroring), and `DownThemAll` (not for recursive web page capturing but for saving embedded and/or linked resources). Especially for the filters of download linked files and in-depth capture. Current filtering mechanism is simply inherit from legacy ScrapBook and ScrapBook X, but I'm still thinking whether it can be further improved.

**Comment by BarbzYHOOL** [comment]
httrack and wget, i cannot get past a login page, with curl i can't but it's useless in that case

your extension helps me but i'm still not able to save all pages, so i'm trying to increase the depth number, let's see
