### ISSUE TITLE
Help! I can't save any pages.

### ISSUE THREAD

**Issue by gred22** [danny0838/webscrapbook#171]
Today, all of a sudden, I get an error message everytime I try to save a web page.  Here is an example:

Capturing (document) [173] https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104505/f-16-fighting-falcon/ ...
Saving data...
Fatal error: Require server app version >= 0.17.0.

There were other "error downloading" lines, but those happen a lot and I took those out.  It's this last, fatal error, in red, that seems to be the issue.  But I don't have any idea what to do to correct this - can you help me?

Mark

**Comment by danny0838** [comment]
As the message says, the server app needs upgrade.  If you are using [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook), you can do it with `python -m pip install -U webscrapbook`, as the doc says.

This is most likely due to auto-update of WebScrapBook by the browser, and newer WebScrapBook requires newer PyWebScrapBook to be compatible.

**Comment by gred22** [comment]
OK, I did that, and then it told me to upgrade pip as well, which I also did.  Everything working fine now - thanks.
