### ISSUE TITLE
[Feature Request] Sorting Folders

### ISSUE THREAD

**Issue by superjkl** [danny0838/webscrapbook#173]
Are there any plans to implement folder sorting so a folder could be sorted by title, url, create time, modify time? I know web extensions limit your ability to interact with the filesystem, so would it be possible to implement this for the server only?

**Comment by danny0838** [comment]
This is technically possible but not yet implemented, as in the [TODO list](https://github.com/danny0838/webscrapbook/wiki/Diffs#limitations).

**Comment by superjkl** [comment]
In the mean time if anyone needs sorting I'm working on a python script to sort folders by manipulating the toc.js file. Use at your own risk! https://github.com/superjkl/webscrapbook-sort

**Comment by danny0838** [comment]
Thank you. Can you try integrating it into PyWSB?

**Comment by superjkl** [comment]
Awesome I'll give it a try!

**Comment by danny0838** [comment]
No, I mean `webscrapbook/scrapbook.py` or `webscrapbook/scrapbook/*.py` for scrapbook scheme related utilities, such as metadata and toc handling. More general utilities can go to `webscrapbook/util.py`.

**Comment by superjkl** [comment]
Lol yes I see now! I realized the server wouldn't already have those utilities as they would all be in the browser extension. Also would it be possible to change toc.js and meta.js to be pure json files instead of javascript since these files will now be interpreted by both the server and browser?

**Comment by danny0838** [comment]
As said in #158, we are considering implement full scrapbook scheme in PyWSB so that it can support full scrapbook manipulation independently (without WSB extension, except for web page capturing, of course). We want the manipulation be available at least through CLI, as it's likely more performant and allows automation. It'd be better also in the backend web interface and WSB interface (as a quick start we can simply pass the instruction from the interface through URL params or forms to same underlying methods and pipe command output to the frontend through SSE stream, until a better implementation has come out).

Using javascript instead of JSON is to allow pure static access locally without a browser tuning (AJAX is not available through file: protocol due to the restriction of same origin policy). We are not going to change this unless there's a better strategy.

**Comment by superjkl** [comment]
Yes I was thinking it would be much easier for you to implement functionality on the server then send http requests to the server API. Yes I understand the usage of Javascript now, thanks! Since webextentions are so limited when it comes to file access and manipulation I was wondering if there are many users who use webscrapbook without PyWSB. Since it would be much easier to just develop a limited webextension front end where PyWSB does all the heavy lifting.

**Comment by danny0838** [comment]
> Would it be a bad idea to make webscrapbook primarily a python cli app (PyWSB) which uses the web extension as a front end view and web capturer?

I'm not sure what your implication is. Aren't we just doing this? Or you mean implementing front-end interface through PyWSB web interface instead of WSB extension?

**Comment by superjkl** [comment]
Sorry I mean would it be a bad idea to make WSB extension require a running PyWSB server? This would mean WSB extension would not need to directly touch the filesystem at all, but would instead send requests to the server. This would mean many features in WSB extension could be moved to PyWSB. It would be easier to primarily develop PyWSB and avoid duplicate features shared by both PyWSB and WSB. This might be a bad idea though, I'm just wondering if this is possible.

**Comment by danny0838** [comment]
WSB extension cannot touch filesystem due to the restriction of the browser extension framework. We do are trying to making WSB mostly a web page capturer, with a simple switch to determine whether the captured data be sent to PyWSB backend or be downloaded through extension API.

However, there's also a need for scrapbook managing. Managing through web interface is possible, but more limited than browser extension interface, such as no sidebar support, prompting a window is more likely blocked by the browser, being unable to invoke a browser extension action such as locating an item in the sidebar, and being unable to load extension config, such as highlighters for the editor. If such issues can be overcomed, we'd like to make it as less dependent to browser extension as possible.

**Comment by superjkl** [comment]
Sorry I don't mean to implement a web interface on the server. Right now it looks like PyWSB is basically a proxy for the filesystem, instead maybe we should just have a simpler API for PyWSB. The API could be more like a repository pattern, or commands could be given to the server like update, delete, sort. This would be in contrast to the current system which takes GET and POST for specific files in the scrapbook.

**Comment by danny0838** [comment]
@superjkl Sorry for not having been clear. I did asked for an integrated implementation of **sort** feature, presuming that sorting is a relatively simple tool that can probably be implemented as something like `webscrapbook.scrapbook.sort`, similar to current `webscrapbook.scrapbook.cache`, as it's likely a "locate root directory, configs, book and item IDs to sort => read meta and toc => sort => write meta and toc". I did not expect an introduction of a large set of extra custom and/or 3rd party modules and packages.

That's why I said that you can first make a quick implementation of your original code to make it available via PyWSB CLI, and then gradually refactor to make it fit with our code base, with no or limited tweak of shared common libraries.

Whether and how to work on it is still all up to you. But at our position we will only take codes that fit well, or can fit well after a little patch, with our code structure. If it end up being not the case, we would take it as an illustration or reference and rewrite one by ourselves.

Latest devel branch includes shared `webscrapbook.scrapbook.host` and `webscrapbook.scrapbook.book`, which should be able to do most basic IO tasks, and there are also `wsb cache` and `wsb convert` CLI tools ready for use. We are still working on fsck and import/export functionality to make it a competent replacement of the original indexer in WebScrapBook extension, but the shared library is likely not going to change largely.

**Comment by danny0838** [comment]
We are going to implement more high level scrapbook operation API in the backend server, so that it's not merely a proxy to file operation. However there are still some issues to overcome, so it's still in work.

**Comment by danny0838** [comment]
Implemented in 0.87.0
