### ISSUE TITLE
Ideas about reimplementing the legacy note feature?

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#186]
Legacy ScrapBook supports `note` item type, but since ScrapBook X `note page` is introduced in favor. The `note` type in WebScrapBook corresponds to `note page` in ScrapBook X, and the legacy `note` has been renamed to `postit`.

Currently WebScrapBook only supports a very simple interface to view and edit legacy `note` as a plain text note snippet with the first line being its title (since 0.85.0), and doesn't even support a way to create it, unless imported from a legacy scrapbook or created by manually editing the metadata tree files.

Personally I use `note page` primarily and legacy `note` is nearly never used. I have no idea about what the position of a legacy `note` is and how it should be. An email has been sent to ask Gomita, the author of legacy ScrapBook add-on, but he also couldn't provide a clear answer of the legacy note feature.

We are considering to either do something to make `postit` more useful, or to treat it as an legacy item and provid only minimal support...

Is there someone still use legacy ScrapBook notes much? How do you usually use it? And do you have an idea about how it can/should be implemented in WebScrapBook?

**Comment by pascallothar** [comment]
Hello Danny! 
"How do you usually use it?" did you ask. Here is my feedback.
  
For the moment, I am still using Scrapbook X on Waterfox. I am looking to see if I will make the transition to the most modern browser or not.
  
I like the legacy `note` because it is residing in the left sidebar. So I can sometimes take notes or make copy/paste while keeping the content of the window visible. Actually, I use it like a real Post-It, so the new name is IMHO well chosen.
  
In the past, legacy `note` supported richer text, but it is not an important feature. But I would appreciate the possibility of creating `postit` in Webscrapbook as in the last Scrapbook X, be it in simple text (vs rich text).
  
Have a nice week!
Pascal

**Comment by danny0838** [comment]
@pascallothar Thank you for the feedback. We'll check if editing post-its in the sidebar can be properly implemented.

**Comment by danny0838** [comment]
@pascallothar Implemented the feature of editing postit in the sidebar in 0.107.0

**Comment by pascallothar** [comment]
You are doing a great job!
