### ISSUE TITLE
Support large size capture for Chromium

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#200]
WebScrapBook v0.97.0
Chrome Version 88.0.4324.96 (Official Build) (64-bit)

Attempt to save DailyMail webpages result in error wthout page save

Windows 10 Education
20H2
19042.746
Windows Feature Experience Pack 120.2212.551.0

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz
32.0 GB Ram
64-bit operating system, x64-based processor

https://www.dailymail.co.uk/news/article-9170237/Protesters-gather-damage-Democratic-headquarters-Oregon.html

![dailymail wsb 2021-01-21_084847](https://user-images.githubusercontent.com/52141467/105359971-0fb36780-5bc6-11eb-843e-4bf3879aa1c0.png)

**Comment by danny0838** [comment]
This is because the content of the web page to capture exceeds [the size limit of a content message in Chromium](https://stackoverflow.com/questions/31925936/is-there-a-size-limit-like-32bytes-or-64bytes-for-message-passing-between-conte).

A content message is required to pass data from a content script (which runs behind the web page to be captured to get the content) to the background script (which runs in the browser process to handle data saving) of an extension, and, due to the size limit, the text content of the page to be captured cannot exceeds about 50MB.

Unfortunately, this limit cannot be bypassed easily.

I cannot reproduce this issue directly. The page you provides loads content dynamically when the page is scrolled down. Try capturing the page without scrolling down too much may somehow relieve this issue, before we come up a good solution.

**Comment by danny0838** [comment]
Fortunately we have found a workaround. According to our test, capturing or saving a web page with 70MB bytes (in UTF-8) works in 0.143.0, which didn't work in < 0.143.0.

However, although the hard limit for inter-process messaging has been bypassed, Chromium may still crash if it takes up too much memory. This may be dependent on other device or hardware factors.
