### ISSUE TITLE
Choose in what folder the page to be captured will be placed  (when using backend server)

### ISSUE THREAD

**Issue by nik-gr** [danny0838/webscrapbook#202]
I see this was already mentioned before (#161).  How about saving the captured page in the folder that is selected at the sidebar (as long as it is only one selected and it is a folder)?  

In that way regarding choosing folder is very similar with the legacy addon only that you 1st choose the folder. The sidebar is open, you navigate on the tree, click the folder/subfolder  where you want the page to be placed and then choose to capture it. 
It's not the same but it is better than dragging it where you want, especially with a complex tree structure. 

Can be an intermediate solution until/if #37 is solved. Would that be easy to implement?

**Comment by danny0838** [comment]
Unfortunately, due to the multi-processing nature of WebExtension, it's not that easy to get the currently selected item in the sidebar, and this may also confuse the user.

It is already possible to specify the folder to save the capture item by using `Capture as...` with manually adding the `"parentId": <folder-item-id>` to the JSON config, though the user may have to copy the folder item ID or the code snippet beforehand. The batch capture dialog is very flexible and the user can almost do everything by modifying the JSON config, but designing a GUI that supports such rich features is not that easy...

**Comment by nik-gr** [comment]
I see. It would make it easier if there was an option in context menu when right clicking a folder for copying its {ID} and if there was already "capture.parentId"  key in the default json so with a couple of clicks could be done.

I don't know how multi-processing works. Would it be possible any time there is a single selection click event on the tree a check and if that is a folder to force selection of this folder in all windows? I don't think it would create any inconvenience, whatever else was selected it should be easily reselected using the locator icon. Perhaps this behavior as an option that users can enable if they want to?

**Comment by danny0838** [comment]
> I see. It would make it easier if there was an option in context menu when right clicking a folder for copying its {ID} and if there was already "capture.parentId" key in the default json so with a couple of clicks could be done.

A quick way to get item ID(s) is a simple **dragging and dropping**. It should also be possible via Ctrl+V or Ctrl+X, but it seems to require additional clipboard access permission and may break compatibility with older browser versions, and thus needs more evaluation. Prefilling `parentId` seems to be a good idea, but we need to check if it doesn't cause any additional issue.

> I don't know how multi-processing works. Would it be possible any time there is a single selection click event on the tree a check and if that is a folder to force selection of this folder in all windows? I don't think it would create any inconvenience, whatever else was selected it should be easily reselected using the locator icon. Perhaps this behavior as an option that users can enable if they want to?

Due to the multi-processing nature, the capturer dialog cannot access what are selected in the sidebar directly, and needs a complicated code to communicate with the sidebar. As for the designing consideration, I think selecting an item is mostly for viewing and not for capturing an item under it. If we really do so, it may be quite likely to confuse the user...

**Comment by nik-gr** [comment]
About the designing concern you described, that is why I mentioned the possibility to have it as an extra option that users can enable if they choose to but you are the developer and of course in the end it's up to what design approach you find more appropriate.

As for the dragging feature, I wasn't aware of it. The only usable reason to drag from the sidebar into the tab with the default json I can think of, is so to give the parentId. Would it be possible to have a check and if what has been dragged is a valid folder ID to automatically include the parentID with that as its value (perhaps with an error message if a page was dragged instead)? Working like this is actually as close as it can get to have the easiest way to select the folder where you want to save a page

**Comment by danny0838** [comment]
We have added the feature to prefill the `parentId` key for `capture as ...` since 0.99.0, which is available in Firefox but still waiting for review in Chrome and Edge.

**Comment by Mohan-cloud** [comment]
Does creating folders in the sidebar, create one on the backend server too?

**Comment by danny0838** [comment]
> Does creating folders in the sidebar, create one on the backend server too?

Of course it does. Just note that the item folder is a virtual folder that is recorded in the metadata, no filesystem folder is actually created.

**Comment by nik-gr** [comment]
For all users who have a heavy usage with a lot of captured pages and folders it is definitely a more preferred way to give the folder, thank you for implement it. 
If it is doable and not too much of work I hope you'll consider to  follow the approach I mention at the bottom om my previous post, I think it would be the most user friendly way to choose in what folder to capture a page.

**Comment by frps** [comment]
@danny0838
>Due to the multi-processing nature, the capturer dialog cannot access what are selected in the sidebar directly

And the ScrapBee add-on allows user to save the page in selected folder.
Without this feature the add-on is unusable.
I re-installed WSB for FF today since I don't like ScrapBee capturing dialog and absenсe of single-file saving options and quickly remembered why I chose ScrapBee over WSB a year ago.
So it would be nice if you implement few options that prevent WSB daily usage. Saving to latest selected folder, silent windowless backend autostart in Windows, sidebar refresh after the page saving etc.

**Comment by frps** [comment]
Below is the ScrapBee backend install.bat
so it starts automaticaly

`chcp 65001

reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\scrapbee_backend" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts\scrapbee_backend" /d "C:\Users\username\Downloads\scrapbee\scrapbee_backend.json" /f

reg delete "HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\scrapbee_backend" /f
reg add "HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\scrapbee_backend" /d `"C:\Users\username\Downloads\scrapbee\scrapbee_backend.json"` /f

echo done
pause`

**Comment by danny0838** [comment]
> @danny0838
> 
> > Due to the multi-processing nature, the capturer dialog cannot access what are selected in the sidebar directly
> 
> And the ScrapBee add-on allows user to save the page in selected folder.
> Without this feature the add-on is unusable.
> I re-installed WSB for FF today since I don't like ScrapBee capturing dialog and absenсe of single-file saving options and quickly remembered why I chose ScrapBee over WSB a year ago.
> So it would be nice if you implement few options that prevent WSB daily usage. Saving to latest selected folder, silent windowless backend autostart in Windows, sidebar refresh after the page saving etc.

Well, legacy ScrapBook does not have this feature, while it has an alternative way to pick the folder to capture to. As nobody complaining legacy ScrapBook be unusable, I'd consider this a designing issue, and capturing to the sidebar selection doesn't seem to be the best choice so far, as previously mentioned.

**Comment by frps** [comment]
As far as I remember the legacy SB had an even more convenient way  - choosing where to save right from mouse click context menu. And it has top 10-15 list of the most recently used folders to choose from. THAT was handy.

Since none of the current add-ons have this feature (and I don't know why it's not possible) - the next option would be to open sidebar or open overlay window with the folder structure displayed as it done in ScrapBee. Not the most convenient or fastest way, but at least something.
Saving all the captures to the root is the same as copying all users files to disk D:\ root and offering to sort them later. My Scrapbook library contained many thousands of page/clips captures sorted by category. The typical day adds about 20-30 items to the library. And no one would like to sit and sort them in the end of the day, every day.

And yes, I respect the developer's time and effort but it's very frustrating to see how much time is spent on the most complex code parts and you still can't use the product. Saving captures to the common pile is the main show stopper at this point.

**Comment by danny0838** [comment]
@frps Thank you for the feedback. As what you seem to agree, that the way of picking tree or recent used folder in legacy SB more preferred. The only problem is that we haven't come up with a good idea to design the GUI.

Capturing to the last selected item in the sidebar is less preferred and probably won't be the ultimate solution we'll use, and, even if it's not the case, it's still not something that can be easily implemented due to the multi-process nature of the WebExtension framework.

I almost always move an item after captured rather than specify the parent item when performing a capture. I think it's just like sorting emails from an inbox. It's probably an issue of personal preference, and, regrettably, using `capture as` with dragging item to modify the `parentId` key in the JSON config is probably the fastest way to specify a folder to capture into currently.

ScrapBee seems to have implemented many useful features, but most of its implementation are shortcutting and not robust, and that's why we don't choose to implement them (or has implemented much slower). For example:
1. ScrapBee supports Firefox only and does not support Chromium browsers and mobile browsers.
2. ScrapBee does not allow performing a capture if the sidebar is not opened. The captured page item will silently missing if the sidebar is closed before a capture is completed.
3. Installing backend server as a native app and starting it from the browser does not work if the backend server is to be hosted on a remote device, and that's why WSB does not do so.
If you really want an autostart, you can set the `serve.py` as a system service or to run automatically at startup.
If you don't want a command prompt on Windows, you can rename the `serve.py` to `serve.pyw`, but you won't be able to read the log and you'd have to kill the server from the task manager if you want to stop it.

**Comment by pausto** [comment]
Thanks for your development of the Scrapbook.
I have a lot of saved pages (>10k) with a folder structure. It is very convenient to immediately save to the desired folder, as well as see the 5 last used folders (or better 10).

Perhaps this idea has already been considered, I apologize if I repeat:
Perhaps this information can be stored on the internal server itself and not in the browser? And when calling the "capture page as ..." context menu, make a request to the server, where it will return the last used folders (5 folders), or can it even return the folder structure for selection by the user as it was in the old version?
This will allow receiving the last 5 folders from the server parentId, as well as all parantIds with the structure. And the browser will show the selection.
Those. the basic idea is that the online browser makes requests to get the latest folders and structure when the context menu is invoked.
![Screenshot_39](https://user-images.githubusercontent.com/3185083/110205914-62628d80-7ead-11eb-9339-b320ca5fc23c.png)
![Screenshot_41](https://user-images.githubusercontent.com/3185083/110205934-84f4a680-7ead-11eb-8f79-eae8d6d2b3da.png)

**Comment by danny0838** [comment]
@pausto Unfortunately, it's technically not possible to get the context menu show recent folders since WebExtension API does not allow modifying the context menu asynchronously, and a request to the backend server is asynchronous.

**Comment by frps** [comment]
@danny0838 
Is it possible to update context menu when the sidebar is open?

**Comment by danny0838** [comment]
@frps The context menu can be updated at any time except when it's opened by the user. Although it's theoretically possible to detect all scrapbook changing events and update the context menu accordingly, but it's not easy as the backend server may be hosted remotely and there may be other devices modifying the scrapbook. It may require a  a total redesign of the backend server, which is not likely to happen in the near future.

**Comment by frps** [comment]
>The context menu can be updated at any time 
Great.

I think you don't have to modify the backend code. See the suggested solution below.

---- Regarding other devices etc - it can also happen when you open sidebar and someone somewhere modified backend database content. So I'd put this problem out of this topic. ----


in case of "sidebar is open"
1) you allow the user to choose the folder in sidebar he wants to put the page/clip in
2) the app saves the page to choosen folder
3) the app updates or insert the **folder id** from above, **access date** and/or **counter id**++ to firefox webstorage.
4) the app updates the context menu with the 10 last accessed folders.

in case "sidebar is closed"
1) the user makes his choice from context menu folder shortlist
2) app saves the page to chosen folder
3) the app updates or insert the **folder id** from above, **access date** and/or **counter id**++ to firefox webstorage.

Hope this helps

**Comment by danny0838** [comment]
@frps Although it's possible to record recently chosen folder IDs and update the context menu, it's possible that the metadata of the folders be modified before the user opens the context menu, and the items displayed in the context menu could thus be outdated.

**Comment by frps** [comment]
And someone could modify the file I opened in my Libre Office.
And the disk can be erased while I'm watching a movie.
And the site may disappear while I'm downloading a file.

The file system makes no guarantees that it will be the same by the time you write to it.

It is not the add-on problem. Absolutely.

No folder? Just throw an error message and that's it.

**Comment by pausto** [comment]
> @pausto Unfortunately, it's technically not possible to get the context menu show recent folders since WebExtension API does not allow modifying the context menu asynchronously, and a request to the backend server is asynchronous.

As far as I understand, the browser extension stores all information about the folder tree and all saved pages. The meta and toc files. This data is used in "Show hint when browsing a page having been captured".
The extension periodically contacts the server, checking whether the data has changed. If changed, it loads again. Together with this data, it is possible to store for a specific user
the latest folders on the server, download to the browser and receive from the server if they have changed, similar to other data Or am I wrong?

**Comment by pausto** [comment]
> It is not the add-on problem. Absolutely.
> 
> No folder? Just throw an error message and that's it.

I completely agree. This is not a problem, you can just show an error on save if the structure has changed.
For personal use, this is not a problem 100%

**Comment by danny0838** [comment]
> And someone could modify the file I opened in my text editor.
> And the disk can be erased while I'm watching a movie.
> And the site may disappear while I'm downloading a file.
> 
> And the file system makes no guarantees that it will be the same by the time you write to it.
> 
> It is not the add-on problem. Absolutely.
> 
> No folder? Just throw an error message and that's it.
> 

Yes, all issues like these are undesired, and we have to do many things to avoid them from happening or provide an adequate detection and error handling. Even error handling is quite a few work. Without it the app can simply crash.

The problem of folder ID being out of date can be something like showing a folder with an outdated title, causing the user to put a captured item into a totally unexpected folder. Things like this won't throw an error, but misleading enough.

> > Although it's possible to record recently chosen folder IDs and update the context menu
> 
> This is exactly what we are missing in the app and we ask for it to be added. And it was perfectly implemented in the old Scrapbook and we would like to see it implemented in the new one to make it comfortable to use.

I know. The thing I'm telling is that WebExtension works differently with legacy Add-on, and many things can just not be easily implemented as before.

As mentioned before, I don't even think displaying recent used folders in the context menu a good design approach. 

The approach we're considering is to provide a helper button, which pops a dialog for the user to select a scrapbook folder (or a recently used folder), in the "capture as" dialog window. This is still not easy to implement, though.

**Comment by frps** [comment]
>displaying recent used folders in the context menu a good design approach

I was quite satisfied with it in the old Scrapbook and missing the oprion in the current re-makes.
It takes less clicks than a helper button and more convenient for the active use.

Right now I am using the ScrapBee add-on since a saving a page to a big pile in the current WSB version doesn't suit me at all. 
And I save A LOT of pages/clips daily. I am not happy with the button on the toolbar or Save Advanced context menu with the folder tree popup. I want a one click solution. It DOES matter.

**Comment by danny0838** [comment]
> > @pausto Unfortunately, it's technically not possible to get the context menu show recent folders since WebExtension API does not allow modifying the context menu asynchronously, and a request to the backend server is asynchronous.
> 
> As far as I understand, the browser extension stores all information about the folder tree and all saved pages. The meta and toc files. This data is used in "Show hint when browsing a page having been captured".
> The extension periodically contacts the server, checking whether the data has changed. If changed, it loads again. Together with this data, it is possible to store for a specific user the latest folders on the server, download to the browser and receive from the server if they have changed, similar to other data. Or am I wrong?

No, the extension contacts with the server every time when the user browses a new address, though there's a caching mechanism and the server will simply response a 304 if the scrapbook data is not changed. The connection do cost some time, and fortunately showing captured page numbers isn't something that needs to react immediately.

It's a totally different story for the context menu. The context menu must response immediately when the user opens it, and the API simply doesn't allow an asynchronous response to build the menu dynamically after contacting with the server.

**Comment by frps** [comment]
>the API simply doesn't allow an asynchronous response to build the menu dynamically after contacting with the server.

It is not required to rebuild a menu.

Also I am absolutely sure that 99.9% of your users use it in a individual mode on the same PC.

**Comment by danny0838** [comment]
> > the API simply doesn't allow an asynchronous response to build the menu dynamically after contacting with the server.
> 
> It is not required to contact the backend to rebuild a menu. It should be rebuilt already on the last saving session.
Well, it's required. Without contacting the server the extension can even not know what title of a folder ID is. We do can cache the folder title with the ID, and it may be outdated and misleading when the menu is shown, as previously said.

Another designing issue is how to select a folder to save a capture? Reading the currently selected item in the sidebar may be undesired as previously mentioned. Maybe a new context menu command to set an item as the "inbox"?

> > displaying recent used folders in the context menu a good design approach
> 
> I was quite satisfied with it in the old Scrapbook and missing the oprion in the current re-makes.
> It takes less clicks than a helper button and more convenient for the active use.
> 
> Right now I am using the ScrapBee add-on since a saving a page to a big pile in the current WSB version doesn't suit me at all.
> And I save A LOT of pages/clips daily. I am not happy with the button on the toolbar in the ScrapBee or Save Advanced context menu with the folder tree popup. I want a one click solution. It DOES matter when you use it up to 100 times a day.

Thank you for the feedback. Unfortunately we still have so many issues to deal with and we have to prioritize them, and a core functionality is generally prior than a new UI for convenience, especially one not seeming easy to implement.

**Comment by frps** [comment]
>Another designing issue is how to select a folder to save a capture?

For the open sidebar mode - check the current ScrapBee or the old pre-WebExtension Scrapbook.
For the closed sidebar mode - check the old Scrapbook.

>We do can cache the folder title with the ID, and it may be outdated and misleading when the menu is shown, as previously said.

Even Windows does not guarantee that the disk or file you have seen a moment ago still accessible. Why should you?

**Comment by danny0838** [comment]
> > Another designing issue is how to select a folder to save a capture?
> 
> For the open sidebar mode - check the current ScrapBee or the old pre-WebExtension Scrapbook.

The problem of the ScrapBee approach is mentioned before.

I don't see a mechanism to select a sidebar item for capturing in legacy ScrapBook. Do I miss something?

> For the closed sidebar mode - check the Scrapbook X screenshot above.

Which screenshot do you mean? We do are considering the helper button approach in the capture as dialog. The problem of the context menu approach is also mentioned before.

> > We do can cache the folder title with the ID, and it may be outdated and misleading when the menu is shown, as previously said.
> 
> Even Windows does not guarantee that the disk or file you have seen a moment ago still accessible. Why should you?

I don't think they are the same. Selecting a folder that is no more exist can be easily detected and just response an error. Capturing an item into a totally unexpected folder (due to a bad showing name) is not auto-detectable and the user may have difficulty to find it. I think the latter is even worse then the former.

> 
> > and a core functionality is generally prior
> 
> Saving to a choosen folder is a core functionality for sure. Would you like to have a disk where you have to sort and move files from the disk root every time you copied something to it?

WSB allows you to pick a target when moving or copying a items, anyway. Current WSB works more like having all new emails in the inbox (although it's actually the root folder), or having all files downloaded to the default download folder. It's not perfect but I don't think it's that bad. Actually it's what I almost always do, as mentioned before.

**Comment by danny0838** [comment]
We have added a new feature of dragging a toolbar button capture command into the sidebar to invoke a capture into a specific scrapbook position in version 0.101. The dragged command is basically a proxy of all selected tabs and this is basically a compensation for the inability to drag tabs into a page in the WebExtension framework.

**Comment by pausto** [comment]
> We have added a new feature of dragging a toolbar button capture command into the sidebar to invoke a capture into a specific scrapbook position in version 0.101. The dragged command is basically a proxy of all selected tabs and this is basically a compensation for the inability to drag tabs into a page in the WebExtension framework.

Thanks for your work
Updated version of Webscrapbook in Firefox to 0.101.
Please tell me where to find this button in the sidebar. I have not found any changes
thank

**Comment by pausto** [comment]
Understood, looked at the code changes. It is necessary to drag out the menu item.
![Screenshot_44](https://user-images.githubusercontent.com/3185083/110279163-3826e200-800b-11eb-8c11-a155dbf6d41c.png)

**Comment by nik-gr** [comment]
nice addition, more or less provides the functionality I was askinf for thanks. 
Not the dragging feature I had in my mind but does the same thing and potentially a better implementation. The only thing missing is a title field on the 'edit tab' toolbar so we can also choose the title of each capturing page if we  don't want the automatic one.
To have a more convenient way to use the drag-capture option I moved the addon icon on the left side just above the webscrabook sidebar. But the options menu that opens after clicking the addon icon hides the top of the sidebar. Will it be possible to add a functionality so the options menu will close when the dragging button starts to be dragged?


As for a recent folders list discussion that started above, I don't really see why is difficult to implement.
I mean to capture a page requires a connection to the server right? so why not have a check first if the ID exists and the title of that ID is still the same. If not just an appropriate message to the user either informing about the modification and asking to proceed or not, or  explaining that the folder has been deleted (or even a more detailed check if the folder has been moved to another X folder if you consider that of importance) and updating the context menu accordingly. 
An other way to keep context menu updated besides the asynchronous issue is by modify it every time a recent folder is changing by checking if the mentioned ID is included in the recent folders IDs, if it does just update/remove it from there. With such approach context menu will always be updated as long as there is only one user connected to the database which I think is how everyone is using it. If it is supported to have more than one users connected, I am not sure even if it should be in the scope of the addon, I mean leagacy addon couldn't and didn't have it and now that it is doable it is above of non-proffesional usage and of an average user usage case, it can be an extra paid feature for those who want it and in any case it's an issue need to be solved for all the approaches that save anywhere but the root folder.

**Comment by frps** [comment]
@nik-gr it is not a tech problem but social.
I'd suggest to move to another Scrapbook clone https://addons.mozilla.org/en/firefox/addon/scrapbee/
The folder is selectable on saving (Save Advanced menu), and the sidebar updates itself in contrast to this one.
The backend starts automatically also. It's far from perfect but usable at least.

**Comment by danny0838** [comment]
@nik-gr 
> The only thing missing is a title field on the 'edit tab' toolbar so we can also choose the title of each capturing page if we don't want the automatic one.

Generally the editor is for editing the web page and not the metadata of the related item. Though the captured item title defaults to the web page title if not otherwise specified, and you can right-click on the save button and edit the web page title from a dropdown command.

To specify the captured item title regardless of the original web page title, use "capture as" and set the "title" key.

> Will it be possible to add a functionality so the options menu will close when the dragging button starts to be dragged?
No, unfortunately. The dragging will be canceled immediately if the dragged element is hidden or the source page/window is closed.

Oops, I haven't thought of this awful issue. Not sure if it's possible to temporarily shrink the dropdown menu during a dragging. Before there's a solution you can try opening a manage window for easier dropping.

**Comment by nik-gr** [comment]
@frps thanks for the suggestion, I'm aware of it. About addon variations (there is also scrapyard), the additions I see in webscrapbook compare to the legacy addon are good although not really of importance for my way of using it. The ideal for me would be to be able to use some addon to capture pages in such way that would be compatible with the legacy addon so that I can use my scrapbook offline on some older browser with the leagacy addon. It is simple, stable, I know it, it does what I want, I'm used to it, I know it won't break. 

Closer to that it is scrapbee but still not exactly there (developer changed the syntax type for the folder IDs for reasons I cannot understand), also it is a little buggy and it does not provide a way to capture in page linked files. The developer doesn't seem to be very active so I'm not very confident he will improve those things or fix something that might break in the future. The guys here are the same behind scrapbook x, they are definetely active and do some serious work on it. 

What I'm most interested in is to have a way to continue using my very old and very big scrapbook with the features and performance that the legacy addon provided and fill confident that the tool I will choose won't break in the future. As for the time being I'm using both addons until I decide what suits me best

**Comment by nik-gr** [comment]
@danny0838  
> you can right-click on the save button and edit the web page title from a dropdown command.

That is exactly what I wanted, I don't need to see it on the toolbar just to be able to have my own title instead of renaming it afterwards (btw is that changing tilte feature documented somewhere? I couldn't find it)

About options menu getting in the way, it's not that big of an issue since there are workarounds but if it can be solved it will be a welcomed imporvement, maybe while dragging the element the rest of the elements can be hidden/folded?

**Comment by danny0838** [comment]
@nik-gr We do have a [changelog](https://github.com/danny0838/webscrapbook/blob/master/CHANGELOG.md), but it is updated lazily before version 1.0 and not every details are documented.

Although it's possible to just support the legacy ScrapBook scheme, WSB has chosen to change it in the very early development stage to support many good features and to fix several issues of the legacy ScrapBook. PyWSB provides  a bidirectional conversion tool for migration, though there are some caveats and it's not fully equivalent to accessing the same database in a compatible way.

We are curious about in what situation would you still choose to use legacy ScrapBook? WSB should have implement almost all functionalities of the legacy ScrapBook, except that some GUI are still under development and less user friendly.

> maybe while dragging the element the rest of the elements can be hidden/folded?

This is exactly what I've said "to temporarily shrink the dropdown menu during a dragging" for. It needs further testing and evaluation, though.

**Comment by nik-gr** [comment]
> We are curious about in what situation would you still choose to use legacy ScrapBook?

That is a good question, the main drawbacks for me was the save folder issue that is discussed here (and basically solved) and the inability to navigate with arrow keys and multiselecting with space bar on the tree which I was pleasantly surprised to see that had also been implemented. 
So it's more about to feel comfortable using webscrapbook before transform my scrapbook to it. There are many years of storage there and I don't want to have to re-organize, probably re-capture and re-annotate as well, every new page in case something goes wrong with webscrapbook

(one thing that it can become more user friendly is the tab that displays the json when you choose "Capture tabs as...", but not a reason for not using webscrapbook)

**Comment by danny0838** [comment]
@nik-gr Thanks for the feedback. [Convertion tool](https://github.com/danny0838/webscrapbook/wiki/FAQ#can-i-use-webscrapbook-with-data-made-from-legacy-scrapbook-x) from and to legacy SB is available, and you probably don't need to do much for migration.

For better security you can prepare a nice diff tool at hand to check if there's anything go wrong  during the convertion. If you don't have one in mind, consider WinMerge2011 or Git.

**Comment by danny0838** [comment]
Thank you for the feedback. The next step is to implement a better GUI for "capture as", which will be traced in #37.

**Comment by nik-gr** [comment]
Hi @danny0838 , thanks for implementing it and for all the nice work you are doing with this addon. 

When you'll have the time if you can add the functionality to minimize/shrink the popup menu when capturing by dragging, that would perfected this feature (perhaps on a right click dragging to not mess with other functionality), hopefully it can be done, but still even without it, the feature is nice, thanks

**Comment by danny0838** [comment]
@nik-gr This should be implemented in 0.107.0. Check if it works.

**Comment by nik-gr** [comment]
> 
> 
> @nik-gr This should be implemented in 0.107.0. Check if it works.

@danny0838 I know it is a very delayed respond but I wanted to say thanks (yes it works 👍)
