### ISSUE TITLE
[Feature Request] Draging & Dropping icons to WebScrapBook icon to Capture actual dragged page icons

### ISSUE THREAD

**Issue by Atanacius** [danny0838/webscrapbook#21]
... Not sure if it's clear.

But take an example:
In ScrapBook X we can drag & drop the "favicon" icon to ScrapBook X panel to.. capture it.
When we keep pushing ALT key, it create a bookmark instead!

.... In WebScrapBook.. It no working like this, so, it's this feature I ask to:

- 1) Dragging a "favicon" icon to the "icon" of WebScrapBook will trigger the opening of the WebScrapBook menu.
 - 2) In this menu, since it's the same as the actual WebScrapBook menu, it's then giving us choices to: Capture TAB, capture TAB (Bookmark) or Capture TAB (source)
- 3) For capturing then, just release the "favicon" dragged on one of these choice.

And then, the TAB is captured like we would want: (physical), (bookmark) or (source) !

Thanks to considering this, as I save MANY often numberous of TABS in old-forme ScrapBook X like that.
It save me many precious seconds, that can become minutes/hours saved !

(the old panel miss me, since now we can't organize our capture in just.. drag & drop... but that's a thing... Firefox 57 is responsible of.. I hate it (Firefox 57))

**Comment by danny0838** [comment]
We'd investigate on it. But this could be impossible due to the limitation of Web Extension framework.

**Comment by Atanacius** [comment]
I understand very well, then do your best.

**Comment by loshran** [comment]
I think this is an unnecessary function if there is a button and the ability to specify tags when saving. By the way, Firefox swears with version 50 on Draging & Dropping.

**Comment by Atanacius** [comment]
It's necessary if you want preserving the ability to quick scrapbooking and organize!
...

**Comment by danny0838** [comment]
Capture via dragging a link (or the address bar icon, which is essentially a link) to the sidebar is implemented in 0.72.0, same as uploading via dragging local file(s) to the sidebar.

A caveat is that dragging a link triggers a "capture link (source)" rather than "capture tab". You can hold Alt for "capture link (new tab)" and Ctrl for "capture link (bookmark)", but neither of them works same as capturing the currently visiting tab, which seems not possible to implement as the address icon doesn't hold the information of the tab, and the tab cannot be dragged in WebExtension framework.
