### ISSUE TITLE
WebScrapBook's Capture page as feature does not work in Firefox Developer Edition

### ISSUE THREAD

**Issue by michellek8xv** [danny0838/webscrapbook#221]
I'm using Firefox Developer Edition 90.0b9 on MacOS Big Sur.

Clicking on Capture Page works, but not Capture Page As, to change the title you have to click on Capture Tabs As when the Webscrapbook icon appears on Firefox. If you click on Capture page as it does not do anything.

Replicated on a clean profile with MultiFirefox, same problem when add-on installed.

Should this feature remain or will it be removed in a future update?

I'm new to using this, not sure if this is a bug or not.

**Comment by danny0838** [comment]
This is a known bug and has been fixed in 0.122 (see [changelog](https://github.com/danny0838/webscrapbook/blob/master/CHANGELOG.md)).

However, Mozilla is slowing down add-on reviewing recently due to unclear reason. See [related forum threads](https://discourse.mozilla.org/c/add-ons/addons-mozilla-org/109). We have already submitted 0.124 but it's still pending review for over a week. 

We have got another self-hosted [beta version](https://github.com/danny0838/webscrapbook/tree/gh-pages) signed (0.124.0b1 is actually same as 0.124). You can consider using it for now, or provide more feedback to Mozilla in the forum threads :p.
