### ISSUE TITLE
Redirection to PDF does not work when capturing as single HTML

### ISSUE THREAD

**Issue by gtothill** [danny0838/webscrapbook#235]
I notice that if I save a web page which is entirely a PDF then the PDF does get saved to the server.
On retrieving the page I see the message ..... Redirecting to file Filename.pdf
However the page does not automatically redirect and to view the PDF I need to right click the link and select Open in new Tab.
It would be good if an automatic redirect did happen.
Am I missing something here?
Thanks in advance for any help,
Regards,

Geoff.

**Comment by danny0838** [comment]
Oh! This is the problem. Single HTML file embeds resources files using data URL, but Chromium-based browsers block links and directions to data URLs because the developers think they are unsafe.

There has been a known issue similar to this. We have updated [the doc](https://github.com/danny0838/webscrapbook/wiki/Issues#chromium-based-browsers) to include this case.

**Comment by gtothill** [comment]
Excellent - thanks for the explanation. I moved to saving as a folder and it works perfectly. Thanks for all your work on this. I use webscrapbook to store reams of clinical research which I can then effortlessly sort, annotate and collate. I haven’t used it long and already I’m not sure how I managed without it.
