### ISSUE TITLE
Updating server index slow

### ISSUE THREAD

**Issue by hermann-san** [danny0838/webscrapbook#282]
Hi, 
I've got Webscrapbook on Windows 10 with Firefox on a Virtual Box VM. HTZ archiving with  a backend server.
Starting from 3500 files upwards, Updating server index  starts to get quite slow.  I assume this is because my files are on  a  file share and 3500 files in a single directory (on a file share)  is too much for the backend server.  Although, with Scrapbook X I had the  same setup and 24.000 files in a single directory and it worked fine. 
Someone has an idea if it's possible to work around this performance issue or is it a Python limitation with the backend server?
Thanks.

**Comment by danny0838** [comment]
How slow is it? Can you provide the log or at least the time spent in the log?

The initial generating of index may take somehow longer, but following updating of a single item (which is mostly automatically run when you capture a new page or create or modify an item) is generally quite fast (usually milliseconds to seconds). This remains true for a scrapbook with around 100k files in the scrapbook directory.

**Comment by hermann-san** [comment]
I've checked with a stopwatch and it takes about 6 - 12 seconds from the time it shows me "updating server index....." until the archiving window dissapears. I'm using UIpath for scripting and that may explain some difference in time and what it sometimes take's longer, but also there are different website with different data. Not sure how much of a difference that makes. 

With a new scrapbook with very little data in it, the indexing process take around 1 second.

My guess is that it's the reduced performance that a  file share has and the index probably takes more data. WIth the old Scrapbook X the scrapbook.rdf (I assume that is the index) has around 17 MB for 24.000 Files, but the webscrapbook fulltext.js has around 50 MB for 4.000 files.   If it needs to transfer every time 50 MB back and forth (100MB in total), it may take so time in a virtual environment with a file share and SSD's,

**Comment by danny0838** [comment]
What do you mean the "archiving window" and how do you open it? Through capturing a page, saving a captured page, or run with the "Run indexer" in the options page?

**Comment by hermann-san** [comment]
I mean the pop-up window that automatically come's up when I press the _capture tabs_  button

**Comment by danny0838** [comment]
This is possibly normal.

What "updating server index" does involves uploading the scrapbook tree and toc data and updating the fulltext cache, plus some error-proof to ensure security of the transaction. Although updating the fulltext cache doesn't involves uploading a 50MB file, it still includes loading, adding, and saving the 50MB file. Adding fulltext index involves scanning and parsing the captured pages, which could be slow.

A 6~12 seconds delay for capturing a web page shouldn't be too bother in most cases as the capturing itself can take much longer. If you really intend to get it faster, consider:
* splitting data into more scrapbooks so that there is less fulltext index for each one;
* capturing pages as folders instead of HTZ archives;
* updating your software and hardware of your device(s).

**Comment by hermann-san** [comment]
I wanted to avoid folders since that will result for me in large number of small files. I assume that I will use one scrapbook for capturing new pages and regularly move the pages to another scrapbook which is not used for capturing pages and can be slow with the index.
Thanks again for your help and advise. 🙏️  🙂️
