### ISSUE TITLE
capturing multiple tabs in firefox

### ISSUE THREAD

**Issue by Tikkoneus** [danny0838/webscrapbook#287]
In Firefox if I select a number of tabs and hit "Capture Tabs" webscrabook begins saving but gets stuck on "Capturing" until each tab becomes active. That is, I select 5 tabs and the first one is active and I click Capture Tabs then I see 
Capturing document 1
Saving data ...
Saved as ...
Updating server index
Done.
Capturing document 2
<long pause. if i do nothing then eventually after ~60 seconds it continues. if I click on tab 2 to make it active and then wsb continues saving immediately>

Any idea what's causing this or how to resolve it? It appears that wsb is trying to obtain the contents of the document and for background tabs there's a long delay but for foreground tabs there isn't?

**Comment by danny0838** [comment]
What is the version of your browser and WSB? Usually a long inactive tab gets discarded and will be skipped with an error during a capture. I do not see the long pause as you described.

**Comment by Tikkoneus** [comment]
Firefox 102.0.1 / WSB 1.4.3.

If the tab has been discarded (e.g. exiting the browser and then restarting it and never loading the tab at all) then I do see an explicit message in WSB that the tab has been discarded.

However, the behavior I describe happens if I have a windows with 30 tabs and I cycle through all of them making sure they're loaded and then select all tabs and use "Capture Tabs."

**Comment by danny0838** [comment]
I cannot reproduce the situation you have described. As far as I have seen, all selected tabs will be captured, no matter shorter or longer, without manually switching between them. How long does it take to capture a page is somehow dependent on the network traffic and the browser internal and cannot be controlled by the extension.

Also note that it may be possible for a larger page to take > 60 seconds to be captured, which may seem like it has been stuck.

**Comment by danny0838** [comment]
Close stale issue due to lack of further information.

**Comment by danny0838** [comment]
@chrizilla Capture tabs should be invoked from the dropdown of the toolbar button rather than the context menu of a tab.

**Comment by danny0838** [comment]
> If the function does not work (or works faulty) in the tab context menu, it should be fixed or removed from there !

Initially the context menu of the tab means for that tab only, just like the context menu in the page. However it seems that some native context menu actions do apply to all selected tabs, we'll check if it's applicable; otherwise we'll simply correct the UI text to "Capture tab".

> 
> Anyway, if in step 2+3 I use the toolbar button dropdown menu instead of the tab context menu, it doesn't solve the problem or change the result in any way unfortunately.

This should not happen. Please check if the URLs of the selected tabs are all valid (invalid URL such as empty tab or extension page will be silently ignored). If that's not the case it's unexpected. But we currently cannot reproduce the issue, please provide a short video demonstrating how you actually so that we can investigate whether somehting is going wrong.

Also note that tabs will be saved as multiple maffs. WSB currently doesn't support saving multiple pages into a multi-entry maff file.

**Comment by danny0838** [comment]
Fixed context menu issue in 2.0.4
