### ISSUE TITLE
可否記住上次選定的保存文件夾以及更加便捷的定位擷取目標文件夾呢？

### ISSUE THREAD

**Issue by minshifu** [danny0838/webscrapbook#299]
您好，非常感謝您的這個擴展，確實對我有很大幫助。有兩個改進小提議，望可考慮。

1）目前好像每次擷取都會默認保存在根目錄，能否增加設置，每次擷取都自動保存到上一次所選擇的文件夾中呢？

2）雖然目前有“ Capture tabs as ”功能提供如下界面，在其中選擇每次想要保存的目標文件夾，但是似乎確實不是很便捷。特別是如果目錄中設置的文件夾層級很多的話，每次擷取都要重新一層一層的篩選找到想要用來保存資料的目標文件夾才可以。能否有一個比較快捷的迅速定位目標文件夾的辦法或界面呢？

再次感謝您！

![image](https://user-images.githubusercontent.com/5119952/200728293-9722fc0b-609c-4b5a-96d0-365d0298fd1c.png)

**Comment by minshifu** [comment]
您好，補充一下。關於上面第二點，即快速定位目標文件夾方面。如果能在點擊擴展按鈕後彈出的菜單界面中，或右鍵菜單中直觀顯示並選擇目標文件夾的話，也許是最便捷的方式，不知道有否可能實現。

![image](https://user-images.githubusercontent.com/5119952/201033443-55082266-4f3a-48ce-9f08-46a3e98b1d4a.png)
![image](https://user-images.githubusercontent.com/5119952/201033613-d4f21b71-9c4d-4a0b-bf9a-049b71bf8f1a.png)

**Comment by grotesque** [comment]
is there a difficult way we can do this today? you know like editing template or ini files or something?

**Comment by danny0838** [comment]
Some related discussions can be found in #202. Creating a "recently picked items" list in the context menu is technically impossible (or at least very difficult).

Adding a "recently picked items" list in the Capture As dialog seems technically possible, but we need more investigation to determine how to implement it.

In legacy ScrapBook (X), the recently picked folders are stored as a file in the scrapbook, but there may be a synchronization issue for WebScrapBook due to the async nature of WebExtension framework. We are considering whether such information should be saved at the extension side instead.

**Comment by danny0838** [comment]
@minshifu 

1) 這要先討論所謂「上次選擇」是什麼。如果是指使用者在側欄選擇或開啟的項目，這有可能導致經常擷取到與使用者意圖無關的項目裡去。這點在前面的 #202 討論串也有談到。

如果是指上次擷取時選擇的項目，這也要定義清楚什麼是所謂的「選擇」。WebScrapBook 支援多種決定擷取項目放置位置的方式，包括從「擷取為…」下拉選擇，拖放選擇，甚至包括用進階設定填入特定的 ID。哪些情況要視為使用者的選擇並加以記錄？

其他就如樓上所提，要把記錄儲存在剪貼薄檔案系統中，或是記錄在瀏覽器套件端等等。

2) 目前相對便捷的方式是拖放擷取至側欄的項目中。可以試試。詳見[說明文件](https://github.com/danny0838/webscrapbook/wiki/Basic-(zh_TW)#%E6%93%B7%E5%8F%96%E7%B6%B2%E9%A0%81)。

**Comment by danny0838** [comment]
@minshifu @grotesque We are implementing this feature for v2.0. This is now avaiable in the beta v2.0.0.19. Feel free to test if it works as expected. For more details see #338.

**Comment by grotesque** [comment]
hi danny,
i'll try it and let you know.

**Comment by danny0838** [comment]
@grotesque Any news about this?

Due to some underlying problems we plan to publish in about a week. If there's no further feedback the standard release will be implemented as-is.
