### ISSUE TITLE
[Questions] about some options

### ISSUE THREAD

**Issue by nik-gr** [danny0838/webscrapbook#322]
About actions with Backend server - checker
There are several options for automatic actions there, I don't want to mess things with my data so I want to confirm a couple of thing before do something. I ran the checker just for logging (all options unchecked) and I have several errors and warnings
1a. `"ID": "modify" property (timestamp1) is older than last modified time of index file (timestamp2)`
I have a lot of these at least some seems to be because of different time zone used or something. As I understand this is going to change the modified field of metadata and nothing else, no new ID etc. Is that right?

1b. `'File "data/ID/index.html" not used as item index'` and `'"ID": not recheable from TOC.'`
These are IDs that have folders at the data folder but are not placed on the WebScrapBook tree. What will happen with these, are they going to be placed in the root folder? what name will be shown? they will keep the same ID?
Actually I can see a couple of the IDs mentioned as not reachable from TOC do not exist at the data folder either

1c. `'"ID": icon "some-icon-url" is an absolute URL'` and `'"ID": missing icon file "data/ID/favicon-name.ico"'`
what will happen with these?
___
2 Is there a way to assure a capture will save everything locally? 
Like when a captured page opens nothing to be loaded from internet (from hidden elements/adds/scripts/css/images/...)? There is an option that I think does that, "Internalize external resources" on right clicking of the save icon on the edit toolbox but it is available only for the captured pages. Is there a way to have this as the default for pages we capture or some other options that can provide it? I understand there is a possibility that the result won't be the same as the original but personally I'ld prefer to have to deal with that (choosing a different capture method in such cases) rather than having to internalize for every page I am capturing
___
3 Can we delete resources?
From what I understand if a page is edited before captured it is captured as is, but if it is edited after has been captured then it just hides whatever you remove (text/html elements). Why? Is there a way to delete everything not displayed anymore like parts of text, images,...?
(On right clicking of the save icon on edit toolbox there is an option "permanently delete all erases (all frames)" which sounds relevant but I haven't figured out what is doing) 
__
4 How can I make a donation?

**Comment by danny0838** [comment]
> About actions with Backend server - checker There are several options for automatic actions there, I don't want to mess things with my data so I want to confirm a couple of thing before do something. I ran the checker just for logging (all options unchecked) and I have several errors and warnings 1a. `"ID": "modify" property (timestamp1) is older than last modified time of index file (timestamp2)` I have a lot of these at least some seems to be because of different time zone used or something. As I understand this is going to change the modified field of metadata and nothing else, no new ID etc. Is that right?
> 

Yes, it does what it says.

Time zone issue is unlikely as the checker will take them into account.

> 1b. `'File "data/ID/index.html" not used as item index'` and `'"ID": not recheable from TOC.'` These are IDs that have folders at the data folder but are not placed on the WebScrapBook tree. What will happen with these, are they going to be placed in the root folder? what name will be shown? they will keep the same ID? Actually I can see a couple of the IDs mentioned as not reachable from TOC do not exist at the data folder either
> 

WSB will generate missing metadata (property) and add them to the root folder. What metadata (such as ID, title) will be generated depends on many things. Basically WSB related metadata will be taken if is's a WSB capture; otherwise many heuristics will be followed to guess them.

> 1c. `'"ID": icon "some-icon-url" is an absolute URL'` and `'"ID": missing icon file "data/ID/favicon-name.ico"'` what will happen with these?
> 

(1) As `Automatically cache icons with absolute URL` says, the icon will be cached and the URL will be replaced with a relative one.

(2) Nothing will happen. This is not an issue that can be automatically resolved. You have to either find the missing icon file and move it to the defined path, or revise the icon property to refer to another icon if it's wrong.

It may be easier to simply test it through running. Be sure to make a full backup of the root data directory. And you can use a diff tool (e.g. Git or WinMerge) to check what is changed after running the automatic fixers.

> 2 Is there a way to assure a capture will save everything locally? Like when a captured page opens nothing to be loaded from internet (from hidden elements/adds/scripts/css/images/...)? There is an option that I think does that, "Internalize external resources" on right clicking of the save icon on the edit toolbox but it is available only for the captured pages. Is there a way to have this as the default for pages we capture or some other options that can provide it? I understand there is a possibility that the result won't be the same as the original but personally I'ld prefer to have to deal with that (choosing a different capture method in such cases) rather than having to internalize for every page I am capturing
> 

Resources files will be captured to local as long as no related capture option is configured not to, so you just need to make sure the options are correctly set. `Internalize external resources` is mostly designed for the user to cache embedded resources that are added by copy and paste with HTML edit mode on (in which case resource files will point to the original absolute URL).

> 3 Can we delete resources? From what I understand if a page is edited before captured it is captured as is, but if it is edited after has been captured then it just hides whatever you remove (text/html elements). Why? Is there a way to delete everything not displayed anymore like parts of text, images,...? (On right clicking of the save icon on edit toolbox there is an option "permanently delete all erases (all frames)" which sounds relevant but I haven't figured out what is doing)

You can manually delete resource files through the web interface of the backend server (which can be quickly accessed through the `View page directory` of the dropdown of the `Locate` editor bar button).

Automatically deleting unused resources is currently not implemented as it's technically very difficult to detect them.

Erasing with the WSB editor tool will hide content rather than deleting it, so that they can be restore through the `revert erased` tools. And "permanently delete all erases (all frames)", as what it says, will permanenty delete the erased contents so that they no more take disk space and can no longer be restored. 

> 4 How can I make a donation?

The link can be found in the web stores.

**Comment by nik-gr** [comment]
Thank you. 
It took me some time to check the results from running the backend checker

I have a couple of strange results: A message for missing index file on some IDs, there is no folder in the data folder for those and when I try to open them in browser there is a 404 not found message BUT the wsb edit tool is displayed at the bottom of the 404 page. If I try to wsb search by ID there is no result for these IDs  

As it seems there are many bookmarks I have from old scrapbook that links to other scrapbooked pages. Can you suggest some easy way to change them so that they'll become bookmarks to wsb server pages? (the ID remains the same)

**Comment by danny0838** [comment]
We need more details for further investigation. Please provide a minimal copy of root data folder that can reproduce the issue, and more details about the issue (such as what exact IDs are in problem).

**Comment by nik-gr** [comment]
Nevermind, it was just a couple of files and most likely I deleted them during organizing and that's what happened (I wasn't aware that edit toolbox appears automatically in all http://localhost:9059/data/X/index.html even if there is not a X folder there)
