### ISSUE TITLE
"Capture selected area" grabs inadequate amount of resources

### ISSUE THREAD

**Issue by leedoyle** [danny0838/webscrapbook#42]
Software: Chromium 63, Linux, WebScrapbook from Google Store

On this [page,](https://github.com/danny0838/webscrapbook) I saved the following text selection:

> s a folder, a single HT

The resulted archive is 2.2MBs large and contains all sorts of image resources, most notably "press-header.jpg" that is 1.0MBs in size. Curiously enough, it is not referenced in the selection's HTML source code.
That makes saving a selection ineffective, slow and rather cumbersome. 

As a temporary solution and/or an alternative method of saving selections I suggest you take a look at this  [Chrome addon](https://chrome.google.com/webstore/detail/save-text-to-file/mkepenkbhepjelljcfiooignmpfgochi), [the github link](https://github.com/bobbyrne01/save-text-to-file-chrome) 

Hereby attached the archive(note I had to change the extension due to github's limitations): 
[GitHub - danny0838_webscrapbook_ A browser addon that captures the web page faithfully with highly customizable configurations. This project inherits from ScrapBook X.zip](https://github.com/danny0838/webscrapbook/files/1621545/GitHub.-.danny0838_webscrapbook_.A.browser.addon.that.captures.the.web.page.faithfully.with.highly.customizable.configurations.This.project.inherits.from.ScrapBook.X.zip)

**Comment by danny0838** [comment]
Capturing a selected area still saves the stylesheets, and thus background images and fonts referenced by the stylesheets are still saved.

You'd have to set the "image background" and "font" options to "save current used" so that background images and fonts that are not referenced by the elements in the selected area are not saved. Note about 2 potential side effects, however:

1. if javascripts are saved, they could dynamically create new elements which need those background images and fonts, which are lost if "save current used" is selected.

2. Currently there's an issue that extension scripts cannot access and parse cross-origin stylesheets, and background images and fonts used by them are lost if "save current used" is selected.

**Comment by danny0838** [comment]
Close stale issue. For issues or comments about "save current", raise another issue.
