### ISSUE TITLE
Only a question : pertinence of HTZ and MAFF packages

### ISSUE THREAD

**Issue by ghost** [danny0838/webscrapbook#51]
Hi,

Web ScrapBook 0.26.2 / Firefox 58.0.2 (x64) / Windows 7SP1 (x64)

I've just installed _Web ScrapBook_ (WSB) in order to save webpages without organizing them in mind. I was running the _Save Page WE_ Firefox extension and it appears that WSB with the option _Save captured data as_ -> _Scripted Single HTML_ renders pages perfectly contrarily to the other extension. I mean complex pages because simple ones never pose an issue.

So: a Web page, a click on WSB toolbar button, and there we go, no fuss, complete page saved.
From there on I linger to understand the pertinence of saving pages in HTZ and MAFF packages. What's the point? You'll need WSB to open them, you won't be able to send such a packaged file to someone who doesn't run WSB... I must be missing something, but what?

Thanks.

**Comment by danny0838** [comment]
There are still some limitations for  Scripted Single HTML, such as:

1. They won't work for all web pages due to some technical restriction. For example, a page with a meta refresh in seconds, a sandboxed iframe, a traditional `<frame>`, etc.

2. A modern browser with javascript support turned on is required to view them, and thus they are less cross-platform compatible. In contrary, HTZs and MAFFs can be unzipped and be opened by almost all browsers.

3. An HTZ or MAFF preserves the source data better than a Scripted Single HTML, and convertion of them into raw HTML with supported files is easier.

4. Scripted Single HTML is fatter than HTZ or MAFF.

So, there are still some cases that HTZ and MAFF is more preferable.

**Comment by mazesy** [comment]
I read you clearly, @danny0838 , thanks.
Up to now I haven't encountered any Scripted Single HTML issue, even on complex pages, but I understand your explanation and I'll remember it should I encounter an isue with this package.

Anyway, WSB is a very nice work, need to say, whatever its experimental status. A work in progress as I understand it: it's progressing nicely, and I easily imagine the amount of deep thinking it requires in the face of the webextension's frame.

Enjoying daily. As we say, "keep up the good work"!
