### ISSUE TITLE
[question] webscrapbook在firefox add-on 網站只剩下0.23.0之前的版本

### ISSUE THREAD

**Issue by gakinccc** [danny0838/webscrapbook#53]
Hi,
webscrapbook firefox版在 0.26.2 release當天在addons.mozilla.org可以找到，但是隔天只剩下0.23.0之前的版本
請問是新版在Firefox上有問題還是新版因為某種原因被mozilla給撤掉了?

**Comment by danny0838** [comment]
AMO 官方認為一些版本的 content_security_policy 設定會造成安全風險而在 3/7 下架許多版本。content_security_policy 是為了讓擷取的封存檔案中的 JavaScript 腳本能在「檢視封存網頁」中正常運作，由於 Firefox 架構限制，這些腳本必須在擴充套件的權限下執行，因此可能有風險，我們已經加上 Sandbox 機制避免這些潛在風險。

最近他們的人員主張我們的 Sandbox 機制有漏洞因此下架，我認為他們提出的理由不正確、也已經寫信回覆，對方最後只回應他會再檢查，目前還沒有下文，可能要再等待一段時間。

如果你願意信任我們的處理，可下載最新版本的原始碼，把 src 資料夾用 ZIP 打包成 .xpi 檔案，即可安裝到 Firefox Development Version；或者改用 Chrome 版本。如果你不放心 Sandbox 機制，相關的安全風險只在擷取的網頁含有 JavaScript 才可能發生，你只要不擷取 JavaScript 就不會有危險。

**Comment by danny0838** [comment]
後續發展：雖然他們要求下架的理由是錯誤的，不過我們確實發現了一個相似的安全漏洞，並已在 0.26.3 版本修正。

但我們上傳 0.26.3 版本以後，AMO 官方停用了該版本且堅持要審核完才開放（已經超過 3 週了，他們的速度真是令人不敢恭維……）。AMO 近日也關閉了 beta 頻道的功能。如果您想使用最新版本（並承擔可能的風險），可到[這裡](https://danny0838.github.io/webscrapbook/files/firefox/latest.html)下載我們自行簽署的版本（0.26.3b1 內容和 0.26.3 相同，除了加上 beta 註記及修改 ID 等相關資訊以外；0.26.3 版本程式碼可在這個版本庫中找到）。

**Comment by qdinar** [comment]
hello. little offtopic: i had read this via google translate. as i remember it is about javascript in saved pages. i never saved javascripts. what if you make separate version to put in addons site, with javascripts always not saved? maybe they are going to check it out soon, and publish. then, is not javascript going to create similar issues again in future?

**Comment by danny0838** [comment]
Making a version that never capture web page JavaScript won't work since the web archive file could be modified by the user, who would be able to add JavaScript in it.

A technically possible alternative is to make **a version that uses default content_security_policy only**, just like 0.23.0, which, as a result, would be free of this security concern but most JavaScript in the web archive file won't work when it's viewed using the built-in archive viewer of WSB. If we were to do that, there would be two versions:
1. "normal version": which uses default content_security_policy, and be available in the AMO.
2. "extended version": which uses modified content_security_policy, and released as a a self-signed version which is maintained in our repository and is not visible in the official Firefox addon site.

Though, we really don't want to maintain multiple versions for Firefox just for this. It's just so cumbersome.

**Comment by qdinar** [comment]
i see now that issue is about wsb's viewer. i am not using it now, because, as i see, i have to open that file by browsing with open dialog which is like standard windows folder explorer.

why to use it while i can use just windows explorer? for that aim i have set {save as html} option. so i enter folder and click index.html and it opens in firefox. so, i make 1 extra click and extra search for index.html compared to usage of packed/archived pages.

is there no such problem when opening simple local html file with local javascripts?! because firefox itself saves html with js and opens them, as i know (if javascripts are not disabled in "save full html" in new versions of firefox, i have not checked it).

**Comment by danny0838** [comment]
1. The major benefit for archive format is to reduce file size and amounts, which would be good if one wants to sync the archive web pages using cloud drives, etc. You can open an archive file directly with some setting on Windows (see [here](https://github.com/danny0838/webscrapbook/wiki/View)), but there's currently not a similar way available on mobile.

2. Whether local JavaScripts saved using built-in browser save functionality works depends. Most should run but web traffic related scripts (mostly AJAX) won't work.

**Comment by qdinar** [comment]
i said/meant, in first sentence of last paragraph: why they say that your addon is insecure with local javascripts while firefox already opens files with local javascripts? what is difference?

**Comment by danny0838** [comment]
It's ddifferent because the JavaScript loaded from an archive file cannot run without being under extension privilege, which can do much more than the script of a local web page. We implemented a sandboxing that blocks all potentially danger APIs for the scripts loaded, and  AMO had disabled our addon since they think our sandboxing still has a hole. I respoded that their assertion is wrong with evidence. They said they'll investigate further and there is currently no further response.

**Comment by qdinar** [comment]
"The major benefit for archive format is to reduce file size and amounts"
vs
"an archive file cannot run without being under extension privilege"

- if you *run* something random/{from outside} with privileges that it does not have, you are already like breaking some law/rules/design. it should not be your/addon's job to *run* somthing. addon is not an operating system and not a javascript interpretator/platform.

"We had implemented a sandboxing that"

- that is way around, and your/firefox's addons are not designed/planned to do such things. you are not something like virtualbox/vmware, ie you should not solve/do virtualisation tasks/jobs. why people/users should be sure that a simple addon that should just save page into file can properly do virtualisation?

- so, i think, you should throw away that idea of opening archive files. if firefox does not open them, they should not be opened! some browsers open mht files, and maybe firefox does, if so then save in mht. or other such format. if not, it is not this addon's job by its definition/description.

**Comment by danny0838** [comment]
1. There are other addons doing similar tasks (such as XXXMonkey(s)). As long as the functionality is still provided by and doable with the API of Firefox and its extension system, I don't think we can easily define something as being "not designed or planned to do".

2. Sandboxing IS NOT visualization, and Firefox's native JavaScript also contains a lot of sandboxing, such as local storage, indexedDB, and sandboxed iframes. There are lots of aspects that an addon could have a security concern, sandboxing is only a very small part of them, and that's what addon review is for. As for the security concern: you can choose to wait for AMO's review, review the source code by yourself, or simply don't use it—this applies not only for this addon, but all browser addons.

3. WSB is designed for single or few web page capturing/using/sharing. If you want to capture lots of pages with files reused, you probably need a site copier, such as httrack.

**Comment by qdinar** [comment]
"WSB is designed for single or few web page capturing/using/sharing"
-- i cannot agree with this. there can be hundreds of pages in data folder, it was designed to be so, and its name is "book". and another proof that it is not singe files but big bunch of pages is that page names are not human readable, but just date-time digits.
-- and why did you need to think about this? it is not so hard to reuse local files. maybe you want that every page can be easily selected and moved to another folder with a file manager, but it is alreay not possible due to uncomprehensible file/folder names of saved pages, as i said.

**Comment by qdinar** [comment]
"you probably need a site copier, such as httrack"
-- i would like to gather pages in a folder for several months until its list is hard to scroll, gathering thousand of pages... i will say several examples... there are 5200 folders in 2017-07-26-2018-04-10 folder, and 10595 in 2016-09-09-2017-07-25. there should be lots of css and other file duplicates in every of them, that could be reused within that "scrapbook". i used "multiscrapbook" feature.

**Comment by qdinar** [comment]
as i know even web pages can save data locally in something named webstore or local storage or similar, also can save in cookies. probably extensions have ability to save to some special storage/database locally. if so, that can be used to save files' hashes (md5) and local relative paths, so you can get every new file's local path if it is already saved, by its hash.

**Comment by danny0838** [comment]
Local storage has lots of limitation. It's an old topic discussed, see #2 for detail (especially [this](https://github.com/danny0838/webscrapbook/issues/2#issuecomment-344609087) and [this](https://github.com/danny0838/webscrapbook/issues/2#issuecomment-345299595))

**Comment by qdinar** [comment]
"the extension system cannot read local file system"
-- how indexer works then? probably, it reads folder listing, then it reads contents of files, in order to get page titles.

**Comment by danny0838** [comment]
But the browser cannot read local system directly. It is possible for the browser to read folders and files of a user-dropped folder, but it's probably undesirable for a user to drop the data folder every time when he captures a web page.

**Comment by KrasnayaPloshchad** [comment]
現在情況怎麽樣了？

**Comment by danny0838** [comment]
4/24 其中一位 AMO 管理員回信說他認為沒有安全的方法可以達成我需要的功能，如果我上傳不包含這些功能的版本他們會再檢查。我回詢目前的沙盒機制究竟有什麼安全上的問題，他又回覆他目前無法確定我們的沙盒機制是否安全，要交由安全團隊研究，等有回應會再通知......

簡而言之：他們目前還沒檢查清楚我們的程式碼到底有沒有安全問題就先鎖，目前已經審了快五個月了還沒有明確結論，而且AMO不允許我們上傳新版（除非完全拿掉 content security policy 相關設定）。

我們目前會再給他們幾個月的時間（剛好最近要開發其他東西，沒太多時間碰這個專案），屆時如果被拒絕或無回應，能考慮的大概只剩幾個做法：

1. **Firefox 版套件改為自行簽署，不再發布在 AMO**：Mozilla 對自行簽署的套件要求比較寬鬆，只要能通過自動檢查程式，據官方說法除非已知有害才會封鎖，如此就能維持比較多的功能。不過他們政策最近改來改去，不排除未來有變嚴格的可能......

至於安全性的問題，我們只能說已經盡力把關，目前還沒有任何人回報目前的程式碼寫法有什麼安全漏洞，剩下就比照所有開放原始碼程式的慣例，交由社群公評。

2. **完全拿掉 content security policy 相關設定**：這樣至少 AMO 不會再OOXX......不過一旦拿掉相關 content security policy 設定，按照 Firefox 目前的設定，封存檔中的 JavaScript 在使用WSB內建的「檢視封存網頁」檢視時將完全無法運作，功能上就是缺了一塊。至於 Chrome，由於原始碼維護上的需求，大概也會比照 Firefox 拿掉相關 content security policy 設定。

順帶一提，除了「檢視封存網頁」以外，我們預計要開發的某些功能（允許使用者寫入 JavaScript 腳本控制要擷取或不擷取哪些內容）也會需要動到差不多的 content security policy 設定。如果 AMO 對這方面的處理依舊如此消極，可能很多功能也不能做了。

**Comment by KrasnayaPloshchad** [comment]
如果套件已經自行簽署，那麼還能在 AMO 上發佈嗎？

**Comment by KrasnayaPloshchad** [comment]
如果套件已經自行簽署，那麼還能在 AMO 上發佈嗎？還有，如果有需要的話，能否與他們的安全團隊建立聯繫？

**Comment by danny0838** [comment]
所謂「自行簽署」指的就是不在 AMO 上發布（只申請簽章），需要自己發布在其他地方（例如 GitHub 這裡），經過一些設定也可以做到自動更新。當然更極端的做法是連簽章都不做，不過這樣的套件無法安裝在 Firefox 標準版及 beta 版，只能安裝在 Developer 版。

我們有要求與直接審核者聯繫，不過目前還沒收到回應......

**Comment by KrasnayaPloshchad** [comment]
我知道了，謝謝。不過最近有了新發現，Chrome 版本可以用 Foxified 套件安裝。

**Comment by danny0838** [comment]
我看不到你所謂的論壇。是連結有誤嗎？

**Comment by KrasnayaPloshchad** [comment]
我發錯了，連結應該在這裏，希望您也能聯繫到安全团隊：
https://www.mozilla.org/en-US/about/forums/

**Comment by danny0838** [comment]
AMO 最近的回覆是他們和安全團隊討論後仍認為這樣的機制不夠安全，節錄如下：

> We’ve consulted with our security team and concluded that your sandboxing method unsafe. Deleting a blacklist of global objects to remove access to privileges APIs is not a strong control.

因此，我們決定在最新版本移除 content security policy 設定，Chrome 版本也比照辦理。這意味著未來版本的「檢視封存網頁」會更安全，但無法正常瀏覽含有 JavaScript 的網頁封存檔。

相關的程式碼仍保留著，如有人需要「檢視封存版本」能執行 JavaScript ，可自行抓原始碼加上 Content security policy（Content security policy 設定無法透過附加元件的選項修改，只能寫成獨立的附加元件）。
