### ISSUE TITLE
Automatic site index in Scrapbook folder

### ISSUE THREAD

**Issue by konstruktiv** [danny0838/webscrapbook#63]
At the moment, the generation of the site index and its download as a zip-archive is cumbersome. 

WebScrapBook has the permissions to write to the Scrapbook folder (set in options). Is it possible to automatically generate the site index in the same folder and regularly update the index?

**Comment by olliebean** [comment]
This is the main drawback of this addon at the moment; it really needs to update the index automatically every time a new page is saved - or at least have a menu entry to index the default Scrapbook folder, instead of having to select or drag the folder into the window every time.

Incidentally, to the original poster, if you select the "Auto download updated files" option in the settings, then when you generate the index it will automatically update the index files in the default Scrapbook folder, without having to download them as a zip.
