### ISSUE TITLE
A second button to save the page in one click

### ISSUE THREAD

**Issue by ChrisBertrandDotNet** [danny0838/webscrapbook#76]
I could be a good idea to propose a second button in the customization panel of FireFox, or in the option panel of the extension.
So we would have a second button next to the main button of the extension (which is a menu in fact).
This button could have a floppy disk as an icon. When the user click on it, it would save the page directly in a format that would be selected in the extension settings panel.

The aim is to not enter a menu when we want to save a page. Just click on a button.

**Comment by danny0838** [comment]
Unfortunately, the extension is allowed to have only one toolbar button only.

**Comment by danny0838** [comment]
A possible alternative we can think of is to add an option to turn the toolbar button into a simple button that invokes a capture rather than to show the command list. But it requires a good design and doesn't seems to be a core requirement, so we would pend it until someday we've got time to do the work.

If you simply want a quick way to invoke a capture, consider setting a hotkey using the browser built-in hotkey manager.

**Comment by danny0838** [comment]
Implemented in 0.141.0. When there's only one toolbar command is checked to show in the options, the toolbar button will become a quick button and is invoked with single click. Other useful commands can be invoked through the extension shortkey (managed in the browser built-in extension manager), or the context menu (right-click) of the toolbar button.
