### ISSUE TITLE
Technically possible to Autosave?

### ISSUE THREAD

**Issue by mumbledenoise** [danny0838/webscrapbook#8]
I know you aren't done building out the features for WebScrapbook, but I'm curious, is it technically possible to implement an AutoSave feature, or do the APIs block such behavior?

Thanks for the great extension!

**Comment by danny0838** [comment]
If you mean saving a page on visiting it should be technically possible.

**Comment by mumbledenoise** [comment]
Yes that's what I mean. It's the missing feature stopping me from upgrading to the new Firefox :)

Is there a way I can vote, with my dollars, on specific features?

**Comment by cook2011** [comment]
Just wanted to also request an auto save feature for the new WebScrapbook as in the old Scrapbook X AutoSave addon. Thanks!

**Comment by codeportland** [comment]
Just chiming in to support adding an autosave feature. I'd love to create a searchable archive of every site I've ever visited and this feature would provide the missing link. :)

**Comment by danny0838** [comment]
We are evaluating whether auto capture can be implemented. Could you provide your general usage case? What do you expect about the auto capture feature?

Also, what do you think about other existing implementation, such as ScrapBook X with ScrapBook X AutoSave add-on or SingleFile? Do they fit your needs or still has something you wish to improve?

Auto-invocation of the capturer is not difficult, but there are still many things to consider:
- How to define what to capture? Is duplicated capture OK? If not, how do we exclude them?
- The currently implementation of capturer of WebScrapBook is using an individual extension window, so that it can display full capture log and the user can interrupt the capture process by simply closing it. However, in the case of auto capture, launching a new window for every visiting page is likely too interrupting, and we may have to reimplement the whole capture functionality in the background script. This may be a very large code work, and we need to design a new way to provide the log and the ability to interrupt unwanted capture process.

**Comment by acowdont** [comment]
As a data hoarder, not goot at coding, I added lines in scrapbook/background.js 

  if (!matchTypeAndCount.full) {

    await scrapbook.invokeCapture([{
      tabId: details.tabId,
    }]);
  }

It work but launch a new window for every visiting page. If the capture window isn't focused, the capturer won't work.

**Comment by danny0838** [comment]
@acowdont Use invokeCaptureEx if you want to do that for yourself. But there are still more issues to handle (e.g. as above mentioned) and needs more evaluation.

**Comment by yellowslug** [comment]
>>>   Is there a way to auto save a tab after a configurable time in focus? i do a lot of research and almost always either leave a page quickly or spend several minutes reading? i often forget to save the page until trying to remember it weeks later.

There was an app years ago that saved every page. It was ok, but in about 3 months search and retrieval slowed things down to the point the app was a pain to use. Mb things r better now, i use a paid search tool that indexes several million items, including scrapbook pages. It does logical sub second queries.

Saving pages is what really matters. Setting a timer and saving the page when it expires seems workable. It would cut page saves substantially.

i do not care much about duplicates. Actually, the number of duplicates may yield useful information about the page's importance.

i do not know how to code this, but might be willing to pay someone to do it. Talk to me.

**Comment by danny0838** [comment]
A quick implementation of autosave is done in 0.108.0.

**Comment by danny0838** [comment]
Close issue as it's implemented and no further active discussion.
