### ISSUE TITLE
unable to specify webscrapbook folder on firefox 63.0.3 on linux

### ISSUE THREAD

**Issue by leedoyle** [danny0838/webscrapbook#83]
Browser simply ignores the options setting, saving all archives to its default download folder, ~/Downloads
The browser settings had been not tampered with.

**Comment by danny0838** [comment]
Do you check `Save captured data in ScrapBook`?

**Comment by leedoyle** [comment]
It was set default, i.e. unchecked.

**Comment by danny0838** [comment]
There are still other concerns of defaulting `Save captured data in ScrapBook` to `checked` since `Save captured data as` defaults to `HTZ`, which doesn't work very well with the site indexer.

Another option is defaulting `Save captured data as` to `Folder`, but there are still some issues about if and it doesn't work when `Save captured data in ScrapBook` is unchecked by the user.

**Comment by leedoyle** [comment]
@danny0838  as a temporary solution one could think of a warning or a suggesting tooltip/menu info (e.g. "* note you should enable Save captured data in ScrapBook and ... to zip"). Not an ideal solution though, as it indeed increases the UX difficulty for new users.

**Comment by danny0838** [comment]
The behavior is changed since 39.0. The user can now specify the saved filename (or folder name if saved as folder), with optionally the subdirectory path.
